"""Small, dependency-free localisation helper for the Tkinter interface.

English strings are the source strings used in the code.  Keeping one source
language makes untranslated text obvious and lets contributors add another
language by extending :data:`TRANSLATIONS` without changing the widgets.
"""

from __future__ import annotations

from collections.abc import Iterator
import tkinter as tk


DEFAULT_LANGUAGE = "en"
LANGUAGES = {"en": "English", "es": "Español"}


TRANSLATIONS: dict[str, dict[str, str]] = {
    "es": {
        "pyCoilGen - MRI gradient coil design": "pyCoilGen - Diseño de bobinas de gradiente MRI",
        "Settings": "Configuración",
        "Language": "Idioma",
        "Output directory:": "Directorio de salida:",
        "Browse...": "Examinar...",
        "Tikhonov sweep": "Barrido Tikhonov",
        "Select output directory": "Seleccionar directorio de salida",
        "Full pipeline": "Pipeline completo",
        "Gradient axis:": "Eje gradiente:",
        "Cylinder outer radius [mm]:": "Radio externo del cilindro [mm]:",
        "Cylinder height [mm]:": "Altura del cilindro [mm]:",
        "Ellipsoidal ROI (independent Rx, Ry, Rz)": "ROI elipsoidal (Rx, Ry, Rz independientes)",
        "ROI radius [mm]:": "Radio ROI [mm]:",
        "Levels (turns):": "Niveles (vueltas):",
        "Conductor diameter [mm]:": "Diámetro del conductor [mm]:",
        "Section A:": "Sección A:",
        "Section B:": "Sección B:",
        "Section N:": "Sección N:",
        "Conductor material:": "Material del conductor:",
        "Resistivity [ohm.m]:": "Resistividad [ohm.m]:",
        "Autogenerated hollow cylinder (1 piece)": "Cilindro hueco autogenerado (1 pieza)",
        "Custom printable STL (2 halves)": "STL personalizado para impresión (2 mitades)",
        "STL pair (assets/shells):": "Par STL (assets/shells):",
        "Radial trim (% cable height):": "Recorte radial (% alto del cable):",
        "Gap between layers [mm]:": "Separación entre capas [mm]:",
        "Presets": "Presets",
        "Save preset...": "Guardar preset...",
        "Load preset...": "Cargar preset...",
        "Save preset": "Guardar preset",
        "Load preset": "Cargar preset",
        "Preset saved": "Preset guardado",
        "Preset saved to:\n{path}": "Preset guardado en:\n{path}",
        "Invalid preset": "Preset inválido",
        "Steps": "Pasos",
        "Gradient (pyCoilGen)": "Gradiente (pyCoilGen)",
        "Advanced leads": "Leads avanzados",
        "Show advanced lead parameters": "Mostrar parámetros avanzados de leads",
        "Run pipeline": "Ejecutar pipeline",
        "Stop": "Detener",
        "Stopping...": "Deteniendo...",
        "Cylinder radial section": "Corte radial del cilindro",
        "3D view: shell + ROI": "Vista 3D: carcasa + ROI",
        "Pipeline output": "Salida del pipeline",
        "Clear": "Limpiar",
        "Standalone (one step)": "Standalone (un paso)",
        "Action:": "Acción:",
        "Axis (for wire):": "Eje (para wire):",
        "Levels (wire):": "Niveles (wire):",
        "Outer radius [mm]:": "Radio externo [mm]:",
        "Files": "Archivos",
        "Input STL:": "STL de entrada:",
        "Run step": "Ejecutar paso",
        "Select STL": "Seleccionar STL",
        "All files": "Todos los archivos",
        "Axis:": "Eje:",
        "Height [mm]:": "Altura [mm]:",
        "Levels:": "Niveles:",
        "Coarse points:": "Puntos gruesos:",
        "Fine adjustment": "Ajuste fino",
        "Run sweep": "Ejecutar barrido",
        "Load previous CSV...": "Cargar CSV anterior...",
        "Use selected in Pipeline": "Usar selección en Pipeline",
        "Load previous sweep": "Cargar barrido anterior",
        "Invalid sweep": "Barrido inválido",
        "No sweep result selected": "No hay resultado de barrido seleccionado",
        "Select one result row first.": "Seleccione primero una fila de resultados.",
        "Results": "Resultados",
        "Phase": "Fase",
        "Slope": "Pendiente",
        "Mean error": "Error medio",
        "Missing directory": "Falta directorio",
        "Select an output directory first.": "Seleccione primero un directorio de salida.",
        "Invalid parameters": "Parámetros inválidos",
        "Failed: {error}": "Falló: {error}",
        "Done.\n{payload}": "Listo.\n{payload}",
        "No STL pair is selected in assets/shells.": "No hay un par STL seleccionado en assets/shells.",
        "Select a valid wire STL.": "Seleccione un STL de wire válido.",
        "Select a valid with-leads STL.": "Seleccione un STL with-leads válido.",
        "\n\nAreas with 3 or more cables: {count}. Maximum at one location: {maximum} cables.": "\n\nZonas con 3 o más cables: {count}. Máximo en un mismo lugar: {maximum} cables.",
        "Sweep": "Barrido",
        "Sweep complete": "Barrido completo",
        "Best slope: tk={tk} ({value:.4g} mT/(m.A))\nLowest error: tk={error_tk} ({error:.4g} %)\nCSV: {path}": "Mejor pendiente: tk={tk} ({value:.4g} mT/(m.A))\nMenor error: tk={error_tk} ({error:.4g} %)\nCSV: {path}",
        "No STL pairs in assets/shells (g_Na.stl + g_Nb.stl)": "Sin pares STL en assets/shells (g_Na.stl + g_Nb.stl)",
        "From STL: Rext {outer:.2f} mm  |  Rint {inner:.2f} mm  |  Height {height:.1f} mm": "Del STL: Rext {outer:.2f} mm  |  Rint {inner:.2f} mm  |  Altura {height:.1f} mm",
        "Could not measure the STL: {error}": "No se pudo medir el STL: {error}",
        "Invalid input": "Entradas inválidas",
        "Invalid geometry": "Geometría inválida",
        "Resistivity must be a positive number.": "La resistividad debe ser un número positivo.",
        "ROI outside / colliding with shell": "ROI fuera / colisionando con la carcasa",
        "Alert: {details}": "Alerta: {details}",
        "ROI inside bore (no collision)": "ROI dentro del bore (sin colisión)",
        "Thickness: {value:.2f} mm": "Grosor: {value:.2f} mm",
        "Trim: {value:.0f}%": "Recorte: {value:.0f}%",
        "No STL pair is selected. Place g_Na.stl / g_Nb.stl halves in assets/shells.": "No hay un par STL seleccionado. Coloque las mitades g_Na.stl / g_Nb.stl en assets/shells.",
        "The cylinder outer radius must be greater than cable semi-axis A.": "El radio externo del cilindro debe ser mayor que el semieje A del cable.",
        "The radius, cable height, and layer gap leave the autogenerated cylinder with no usable radial thickness.": "La combinación de radio, alto del cable y separación de capas deja el cilindro autogenerado sin espesor radial útil.",
        "The custom STL has Rint >= Rext; check the halves in assets/shells.": "El STL personalizado tiene Rint >= Rext; revise las mitades en assets/shells.",
        "Cable collision": "Colisión de cables",
        "Result discarded": "Resultado descartado",
        "The result was discarded, so leads and shell were not run.\n\nThe cable generated by pyCoilGen was kept for diagnosis at:\n{path}": "Se descartó el resultado y no se ejecutaron leads ni shell.\n\nEl cable generado por pyCoilGen se conserva para diagnóstico en:\n{path}",
        "Done.\nResults in:\n{path}": "Listo.\nResultados en:\n{path}",
    },
}


class Localizer:
    """Translate source strings and refresh ordinary Tk ``text`` options."""

    def __init__(self, language: str = DEFAULT_LANGUAGE):
        self.language = language

    def set_language(self, language: str) -> None:
        if language not in LANGUAGES:
            raise ValueError(f"Unsupported GUI language: {language}")
        self.language = language

    def translate(self, source: str, **values) -> str:
        template = TRANSLATIONS.get(self.language, {}).get(source, source)
        return template.format(**values) if values else template

    def refresh_widget_tree(self, root: tk.Misc) -> None:
        for widget in _walk_widgets(root):
            try:
                current = widget.cget("text")
            except (tk.TclError, AttributeError):
                continue
            if not hasattr(widget, "_i18n_source_text"):
                widget._i18n_source_text = current
            widget.configure(text=self.translate(widget._i18n_source_text))


def _walk_widgets(root: tk.Misc) -> Iterator[tk.Misc]:
    yield root
    for child in root.winfo_children():
        yield from _walk_widgets(child)
