"""
Pipeline panel — full gradient + leads + shell run.

Lets the user pick the gradient axis, dimensions, Tikhonov, levels, wire
characteristics, and whether to carve into a custom STL or the autogenerated
cylinder / Fusion shell halves. Runs the three steps in a worker thread and
surfaces multi-wire congestion as an accept/reject popup before leads/shell.

Layout: resizable paned windows — parameters | (previews above a permanent
horizontal log). Matplotlib previews stay aspect-locked so they do not distort.
"""

from __future__ import annotations

import math
import os
import tkinter as tk
from tkinter import filedialog, messagebox, ttk
from typing import Optional, Tuple

import numpy as np
from matplotlib.backends.backend_tkagg import FigureCanvasTkAgg
from matplotlib.figure import Figure
from matplotlib.patches import Polygon
from mpl_toolkits.mplot3d import Axes3D  # noqa: F401  — enables projection='3d'

from coilgen.config import (
    CONDUCTOR_MATERIAL_RESISTIVITY,
    Config,
    apply_custom_shell_dims,
    list_shell_pairs,
)
from coilgen.presets import (
    default_preset_dir,
    load_config_preset,
    save_config_preset,
)
from .runner import WorkerRunner
from .units import mm_to_m


class _AspectFrame(ttk.Frame):
    """Container that keeps a child at a fixed width/height ratio while
    centering it inside whatever space the layout gives it.

    Prevents Matplotlib canvases from stretching into unreadable ovals when
    the window is resized.
    """

    def __init__(self, master, aspect: float = 1.0, **kw):
        super().__init__(master, **kw)
        self.aspect = float(aspect)  # width / height
        self.inner = ttk.Frame(self)
        self.inner.place(relx=0.5, rely=0.5, anchor='center')
        self.bind('<Configure>', self._on_configure)

    def _on_configure(self, event):
        w, h = event.width, event.height
        if w < 2 or h < 2 or self.aspect <= 0:
            return
        if (w / h) > self.aspect:
            nh = h
            nw = max(1, int(round(h * self.aspect)))
        else:
            nw = w
            nh = max(1, int(round(w / self.aspect)))
        self.inner.place_configure(width=nw, height=nh)


class PipelinePanel(ttk.Frame):
    def __init__(self, master, get_output_dir, set_output_dir, root):
        super().__init__(master)
        self.get_output_dir = get_output_dir
        self.set_output_dir = set_output_dir
        self.root = root
        self.runner: Optional[WorkerRunner] = None

        self._build()

    def _build(self):
        # Horizontal split: parameters (left) | previews + log (right).
        self.hpaned = ttk.Panedwindow(self, orient='horizontal')
        self.hpaned.pack(fill='both', expand=True, padx=6, pady=4)

        # ---- Left: scrollable controls (only when content overflows) ----
        controls_shell = ttk.Frame(self.hpaned)
        self.hpaned.add(controls_shell, weight=2)

        ctrl_canvas = tk.Canvas(controls_shell, highlightthickness=0,
                                borderwidth=0)
        ctrl_scroll = ttk.Scrollbar(controls_shell, orient='vertical',
                                    command=ctrl_canvas.yview)
        ctrl_canvas.configure(yscrollcommand=ctrl_scroll.set)
        ctrl_canvas.pack(side='left', fill='both', expand=True)
        ctrl_scroll.pack(side='right', fill='y')

        left = ttk.Frame(ctrl_canvas)
        left_window = ctrl_canvas.create_window((0, 0), window=left, anchor='nw')

        def _sync_scroll(_event=None):
            ctrl_canvas.configure(scrollregion=ctrl_canvas.bbox('all'))
            # Hide the scrollbar when everything fits.
            bbox = ctrl_canvas.bbox('all')
            if bbox is None:
                return
            content_h = bbox[3] - bbox[1]
            view_h = ctrl_canvas.winfo_height()
            if content_h <= view_h + 2:
                if ctrl_scroll.winfo_ismapped():
                    ctrl_scroll.pack_forget()
            elif not ctrl_scroll.winfo_ismapped():
                ctrl_scroll.pack(side='right', fill='y')

        left.bind('<Configure>', _sync_scroll)
        ctrl_canvas.bind('<Configure>', lambda e: (
            ctrl_canvas.itemconfigure(left_window, width=e.width),
            _sync_scroll(),
        ))

        self._ctrl_canvas = ctrl_canvas
        self._controls_shell = controls_shell

        def _on_mousewheel(event):
            try:
                containing = self.winfo_containing(event.x_root, event.y_root)
            except tk.TclError:
                return
            w = containing
            while w is not None:
                if w is controls_shell:
                    delta = getattr(event, 'delta', 0)
                    if delta:
                        ctrl_canvas.yview_scroll(int(-delta / 120), 'units')
                    return 'break'
                w = getattr(w, 'master', None)

        def _bind_wheel_tree(widget):
            widget.bind('<MouseWheel>', _on_mousewheel)
            for child in widget.winfo_children():
                _bind_wheel_tree(child)

        self._bind_controls_wheel = lambda: _bind_wheel_tree(left)

        form = ttk.LabelFrame(left, text="Full pipeline", padding=8)
        form.pack(fill='x', pady=(0, 4), padx=(0, 2))
        for col in range(4):
            form.columnconfigure(col, weight=1)

        # Axis
        ttk.Label(form, text="Gradient axis:").grid(row=0, column=0, sticky='w', padx=4, pady=4)
        self.axis_var = tk.StringVar(value='x')
        ttk.Combobox(form, textvariable=self.axis_var, values=['x', 'y', 'z'],
                     state='readonly', width=6).grid(row=0, column=1, sticky='w')

        # Dimensions (GUI in mm; converted to metres for Config / pyCoilGen).
        # In custom-STL mode these entries are hidden; measured labels are shown.
        self.radius_label = ttk.Label(form, text="Cylinder outer radius [mm]:")
        self.radius_label.grid(row=1, column=0, sticky='w', padx=4, pady=4)
        self.radius_var = tk.StringVar(value='39')
        self.radius_entry = ttk.Entry(form, textvariable=self.radius_var, width=10)
        self.radius_entry.grid(row=1, column=1, sticky='w')
        self.height_label = ttk.Label(form, text="Cylinder height [mm]:")
        self.height_label.grid(row=1, column=2, sticky='w', padx=4)
        self.height_var = tk.StringVar(value='170')
        self.height_entry = ttk.Entry(form, textvariable=self.height_var, width=10)
        self.height_entry.grid(row=1, column=3, sticky='w')
        self.dims_readonly_var = tk.StringVar(value='')
        self.dims_readonly_label = ttk.Label(form, textvariable=self.dims_readonly_var)
        # ROI: spherical (R) by default; optional independent Rx, Ry, Rz
        self.roi_ellipsoidal_var = tk.BooleanVar(value=False)
        ttk.Checkbutton(
            form, text="Ellipsoidal ROI (independent Rx, Ry, Rz)",
            variable=self.roi_ellipsoidal_var,
            command=self._toggle_roi,
        ).grid(row=2, column=0, columnspan=4, sticky='w', padx=4, pady=4)

        self.roi_sphere_frame = ttk.Frame(form)
        self.roi_sphere_frame.grid(row=3, column=0, columnspan=4, sticky='we', padx=4)
        ttk.Label(self.roi_sphere_frame, text="ROI radius [mm]:").pack(side='left')
        self.roi_var = tk.StringVar(value='20')
        ttk.Entry(self.roi_sphere_frame, textvariable=self.roi_var, width=10).pack(
            side='left', padx=(4, 0))

        self.roi_ellip_frame = ttk.Frame(form)
        self.roi_ellip_frame.grid(row=3, column=0, columnspan=4, sticky='we', padx=4)
        self.roi_rx_var = tk.StringVar(value='20')
        self.roi_ry_var = tk.StringVar(value='20')
        self.roi_rz_var = tk.StringVar(value='20')
        ttk.Label(self.roi_ellip_frame, text="Rx [mm]:").pack(side='left')
        ttk.Entry(self.roi_ellip_frame, textvariable=self.roi_rx_var, width=8).pack(
            side='left', padx=(2, 8))
        ttk.Label(self.roi_ellip_frame, text="Ry [mm]:").pack(side='left')
        ttk.Entry(self.roi_ellip_frame, textvariable=self.roi_ry_var, width=8).pack(
            side='left', padx=(2, 8))
        ttk.Label(self.roi_ellip_frame, text="Rz [mm]:").pack(side='left')
        ttk.Entry(self.roi_ellip_frame, textvariable=self.roi_rz_var, width=8).pack(
            side='left', padx=(2, 0))
        self._toggle_roi()

        # Optimization
        ttk.Label(form, text="Tikhonov:").grid(row=4, column=0, sticky='w', padx=4, pady=4)
        self.tikhonov_var = tk.StringVar(value='2500')
        ttk.Entry(form, textvariable=self.tikhonov_var, width=10).grid(row=4, column=1, sticky='w')
        ttk.Label(form, text="Levels (turns):").grid(row=4, column=2, sticky='w', padx=4)
        self.levels_var = tk.StringVar(value='12')
        ttk.Entry(form, textvariable=self.levels_var, width=10).grid(row=4, column=3, sticky='w')

        # Wire characteristics
        ttk.Label(form, text="Real cable diameter [mm]:").grid(row=5, column=0, sticky='w', padx=4, pady=4)
        self.cw_var = tk.StringVar(value='2')
        ttk.Entry(form, textvariable=self.cw_var, width=10).grid(row=5, column=1, sticky='w')
        ttk.Label(form, text="Groove height [mm]:").grid(row=5, column=2, sticky='w', padx=4)
        self.a_var = tk.StringVar(value='4')
        ttk.Entry(form, textvariable=self.a_var, width=8).grid(row=5, column=3, sticky='w')
        ttk.Label(form, text="Groove width [mm]:").grid(row=6, column=0, sticky='w', padx=4, pady=4)
        self.b_var = tk.StringVar(value='2')
        ttk.Entry(form, textvariable=self.b_var, width=8).grid(row=6, column=1, sticky='w')
        ttk.Label(form, text="Section N:").grid(row=6, column=2, sticky='w', padx=4)
        self.n_var = tk.StringVar(value='16')
        ttk.Entry(form, textvariable=self.n_var, width=8).grid(row=6, column=3, sticky='w')

        ttk.Label(form, text="Conductor material:").grid(
            row=7, column=0, sticky='w', padx=4, pady=4)
        self.material_var = tk.StringVar(value='Cu')
        material_values = [*CONDUCTOR_MATERIAL_RESISTIVITY, 'Custom']
        self.material_combo = ttk.Combobox(
            form, textvariable=self.material_var, values=material_values,
            state='readonly', width=8,
        )
        self.material_combo.grid(row=7, column=1, sticky='w')
        self.material_combo.bind(
            '<<ComboboxSelected>>', lambda _event: self._on_material_changed())
        ttk.Label(form, text="Resistivity [ohm.m]:").grid(
            row=7, column=2, sticky='w', padx=4)
        self.resistivity_var = tk.StringVar(
            value=f"{CONDUCTOR_MATERIAL_RESISTIVITY['Cu']:.3g}")
        ttk.Entry(form, textvariable=self.resistivity_var, width=10).grid(
            row=7, column=3, sticky='w')

        # Custom STL vs autogenerated
        self.shell_mode_var = tk.StringVar(value='auto')  # 'auto' or 'custom'
        ttk.Radiobutton(form, text="Autogenerated hollow cylinder (1 piece)",
                        variable=self.shell_mode_var, value='auto',
                        command=self._toggle_shell).grid(row=8, column=0, columnspan=2, sticky='w', padx=4, pady=4)
        ttk.Radiobutton(form, text="Custom printable STL (2 halves)",
                        variable=self.shell_mode_var, value='custom',
                        command=self._toggle_shell).grid(row=8, column=2, columnspan=2, sticky='w')

        self._shell_pairs = list_shell_pairs()  # [(label, path_a, path_b), ...]
        self._shell_pair_by_label = {label: (a, b) for label, a, b in self._shell_pairs}
        pair_labels = [label for label, _, _ in self._shell_pairs]
        self.shell_pair_var = tk.StringVar(
            value=pair_labels[1] if len(pair_labels) > 1 else (pair_labels[0] if pair_labels else ''))
        self.shell_pair_label = ttk.Label(form, text="STL pair (assets/shells):")
        self.shell_pair_combo = ttk.Combobox(
            form, textvariable=self.shell_pair_var,
            values=pair_labels, state='readonly', width=16,
        )
        self.shell_pair_combo.bind('<<ComboboxSelected>>', lambda _e: self._on_shell_pair_changed())

        # Radial peel removed from each face after boolean (% of cable radial height).
        self.margin_label = ttk.Label(form, text="Radial trim (% cable height):")
        self.margin_label.grid(row=10, column=0, sticky='w', padx=4, pady=2)
        self.margin_var = tk.StringVar(value='50')
        self.margin_entry = ttk.Entry(form, textvariable=self.margin_var, width=6)
        self.margin_entry.grid(row=10, column=1, sticky='w')
        ttk.Label(form, text="Gap between layers [mm]:").grid(
            row=11, column=0, sticky='w', padx=4, pady=2)
        self.layer_gap_var = tk.StringVar(value='0')
        ttk.Entry(form, textvariable=self.layer_gap_var, width=6).grid(
            row=11, column=1, sticky='w')
        self._toggle_shell()

        # Reusable JSON configurations.
        presets = ttk.LabelFrame(left, text="Presets", padding=6)
        presets.pack(fill='x', pady=4, padx=(0, 2))
        ttk.Button(presets, text="Save preset...", command=self._save_preset).pack(
            side='left', padx=4)
        ttk.Button(presets, text="Load preset...", command=self._load_preset).pack(
            side='left', padx=4)

        # Steps toggles
        steps = ttk.LabelFrame(left, text="Steps", padding=6)
        steps.pack(fill='x', pady=4, padx=(0, 2))
        self.run_gradient_var = tk.BooleanVar(value=True)
        self.run_leads_var = tk.BooleanVar(value=True)
        self.run_shell_var = tk.BooleanVar(value=True)
        self.overlap_var = tk.BooleanVar(value=True)
        ttk.Checkbutton(steps, text="Gradient (pyCoilGen)",
                        variable=self.run_gradient_var).pack(side='left', padx=6)
        ttk.Checkbutton(steps, text="Leads",
                        variable=self.run_leads_var).pack(side='left', padx=6)
        ttk.Checkbutton(steps, text="Shell",
                        variable=self.run_shell_var).pack(side='left', padx=6)

        # Advanced leads (collapsible)
        self.adv_frame = ttk.LabelFrame(left, text="Advanced leads", padding=6)
        self.adv_frame.pack(fill='x', pady=4, padx=(0, 2))
        self.adv_visible = tk.BooleanVar(value=False)
        self.adv_toggle = ttk.Checkbutton(
            self.adv_frame, text="Show advanced lead parameters",
            variable=self.adv_visible, command=self._toggle_advanced)
        self.adv_toggle.pack(anchor='w')
        self.adv_body = ttk.Frame(self.adv_frame)
        ttk.Label(self.adv_body, text="lead_blend [mm]:").grid(
            row=0, column=0, sticky='w', padx=4, pady=2)
        self.lead_blend_var = tk.StringVar(value='15')
        ttk.Entry(self.adv_body, textvariable=self.lead_blend_var,
                  width=10).grid(row=0, column=1, sticky='w')
        ttk.Label(self.adv_body, text="cs_blend_rings:").grid(
            row=0, column=2, sticky='w', padx=8, pady=2)
        self.cs_blend_rings_var = tk.StringVar(value='20')
        ttk.Entry(self.adv_body, textvariable=self.cs_blend_rings_var,
                  width=6).grid(row=0, column=3, sticky='w')
        ttk.Label(self.adv_body, text="junction_rigid_steps:").grid(
            row=0, column=4, sticky='w', padx=8, pady=2)
        self.junction_rigid_steps_var = tk.StringVar(value='4')
        ttk.Entry(self.adv_body, textvariable=self.junction_rigid_steps_var,
                  width=6).grid(row=0, column=5, sticky='w')
        self._toggle_advanced()

        # Run bar
        bar = ttk.Frame(left)
        bar.pack(fill='x', pady=(4, 2), padx=(0, 2))
        self.run_btn = ttk.Button(bar, text="Run pipeline", command=self._on_run)
        self.run_btn.pack(side='left')
        self.stop_btn = ttk.Button(bar, text="Stop", command=self._on_stop)
        self.progress = ttk.Progressbar(bar, mode='determinate', maximum=100,
                                        length=160)
        self.progress.pack(side='left', padx=8, fill='x', expand=True)

        # Wheel scrolling over any control widget (entries, labels, …).
        self._bind_controls_wheel()

        # ---- Right: previews on top, permanent log below ----
        right_pane = ttk.Frame(self.hpaned)
        self.hpaned.add(right_pane, weight=3)

        self.right_vpaned = ttk.Panedwindow(right_pane, orient='vertical')
        self.right_vpaned.pack(fill='both', expand=True)

        preview_pane = ttk.Frame(self.right_vpaned)
        self.right_vpaned.add(preview_pane, weight=4)

        preview_split = ttk.Panedwindow(preview_pane, orient='horizontal')
        preview_split.pack(fill='both', expand=True)

        cylsec = ttk.LabelFrame(preview_split, text="Cylinder radial section",
                                padding=4)
        preview_split.add(cylsec, weight=1)
        self._cyl_figure_setup(cylsec)

        geo3d = ttk.LabelFrame(preview_split, text="3D view: shell + ROI",
                               padding=4)
        preview_split.add(geo3d, weight=1)
        self._geo3d_figure_setup(geo3d)
        self._preview_split = preview_split

        for var in (self.radius_var, self.height_var, self.cw_var, self.a_var,
                    self.b_var, self.margin_var, self.layer_gap_var,
                    self.roi_var, self.roi_rx_var, self.roi_ry_var,
                    self.roi_rz_var):
            var.trace_add('write', lambda *_: self._redraw_previews())
        self._redraw_previews()

        # Permanent horizontal log under both figures.
        self.log_frame = ttk.LabelFrame(self.right_vpaned, text="Log", padding=4)
        self.right_vpaned.add(self.log_frame, weight=1)

        log_bar = ttk.Frame(self.log_frame)
        log_bar.pack(fill='x', pady=(0, 2))
        ttk.Label(log_bar, text="Pipeline output").pack(side='left')
        ttk.Button(log_bar, text="Clear", width=8,
                   command=self._clear_log).pack(side='right')

        log_body = ttk.Frame(self.log_frame)
        log_body.pack(fill='both', expand=True)
        self.log_text = tk.Text(log_body, height=6, wrap='word')
        self.log_text.pack(side='left', fill='both', expand=True)
        sb = ttk.Scrollbar(log_body, command=self.log_text.yview)
        sb.pack(side='right', fill='y')
        self.log_text.configure(yscrollcommand=sb.set)

        self.runner = WorkerRunner(self.log_text, self.progress, self.root)

        # Sensible initial sash positions once the window has a real size.
        self.after(80, self._init_sashes)

    def _toggle_advanced(self):
        if self.adv_visible.get():
            self.adv_body.pack(fill='x', padx=4, pady=4)
        else:
            self.adv_body.pack_forget()

    def _init_sashes(self):
        """Place paned-window sashes once the layout has a real size."""
        try:
            total_w = self.hpaned.winfo_width()
            if total_w > 100:
                # ~42% controls / ~58% previews+log
                self.hpaned.sashpos(0, int(total_w * 0.42))
            if hasattr(self, '_preview_split'):
                pw = self._preview_split.winfo_width()
                if pw > 100:
                    self._preview_split.sashpos(0, pw // 2)
            if hasattr(self, 'right_vpaned'):
                rh = self.right_vpaned.winfo_height()
                if rh > 120:
                    # ~72% figures / ~28% log
                    self.right_vpaned.sashpos(0, int(rh * 0.72))
        except tk.TclError:
            pass

    def _clear_log(self):
        self.log_text.delete('1.0', 'end')

    def _save_preset(self):
        try:
            cfg = self._build_cfg()
        except (ValueError, KeyError) as exc:
            messagebox.showerror(self.root.tr("Invalid parameters"), str(exc))
            return
        directory = default_preset_dir()
        os.makedirs(directory, exist_ok=True)
        initial = f'{cfg.design_folder}.json'
        path = filedialog.asksaveasfilename(
            title=self.root.tr("Save preset"), initialdir=directory,
            initialfile=initial, defaultextension='.json',
            filetypes=[("JSON", "*.json")], parent=self.root)
        if not path:
            return
        save_config_preset(
            cfg, path, name=os.path.splitext(os.path.basename(path))[0],
            source='pipeline',
        )
        messagebox.showinfo(
            self.root.tr("Preset saved"),
            self.root.tr("Preset saved to:\n{path}", path=path),
            parent=self.root,
        )

    def _load_preset(self):
        directory = default_preset_dir()
        os.makedirs(directory, exist_ok=True)
        path = filedialog.askopenfilename(
            title=self.root.tr("Load preset"), initialdir=directory,
            filetypes=[("JSON", "*.json"),
                       (self.root.tr("All files"), "*.*")], parent=self.root)
        if not path:
            return
        try:
            cfg = load_config_preset(path)
            self.apply_config(cfg)
        except (OSError, ValueError, TypeError) as exc:
            messagebox.showerror(
                self.root.tr("Invalid preset"), str(exc), parent=self.root)

    @staticmethod
    def _mm_text(value_m: float) -> str:
        return f'{value_m * 1000.0:g}'

    def apply_config(self, cfg: Config) -> None:
        """Populate Pipeline controls from a preset or sweep configuration."""
        self.axis_var.set(cfg.gradient_axis)
        self.tikhonov_var.set(f'{cfg.tikhonov_factor:g}')
        self.levels_var.set(str(cfg.num_levels))
        self.radius_var.set(self._mm_text(cfg.cylinder.radius))
        self.height_var.set(self._mm_text(cfg.cylinder.height))
        self.cw_var.set(self._mm_text(cfg.wire.conductor_width))
        self.a_var.set(self._mm_text(cfg.groove_radial_height))
        self.b_var.set(self._mm_text(cfg.groove_tangential_width))
        self.n_var.set(str(cfg.wire.cross_section_n))
        self.material_var.set(cfg.fasthenry.material)
        self.resistivity_var.set(f'{cfg.fasthenry.specific_conductivity:.6g}')
        self.layer_gap_var.set(self._mm_text(cfg.winding.layer_gap_mm))
        self.margin_var.set(f'{cfg.shell.auto_margin_pct * 100.0:g}')

        ellipsoidal = not (
            math.isclose(cfg.target.rx, cfg.target.ry)
            and math.isclose(cfg.target.rx, cfg.target.rz)
        )
        self.roi_ellipsoidal_var.set(ellipsoidal)
        self.roi_var.set(self._mm_text(cfg.target.rx))
        self._toggle_roi()
        self.roi_rx_var.set(self._mm_text(cfg.target.rx))
        self.roi_ry_var.set(self._mm_text(cfg.target.ry))
        self.roi_rz_var.set(self._mm_text(cfg.target.rz))

        self.run_gradient_var.set(cfg.control.run_gradient)
        self.run_leads_var.set(cfg.control.run_leads)
        self.run_shell_var.set(cfg.control.run_shell)
        self.lead_blend_var.set(self._mm_text(cfg.leads.lead_blend))
        self.cs_blend_rings_var.set(str(cfg.leads.cs_blend_rings))
        self.junction_rigid_steps_var.set(str(cfg.leads.junction_rigid_steps))

        matching_label = ''
        if cfg.shell.use_custom_stl:
            wanted = {
                os.path.normcase(os.path.abspath(path))
                for path in (cfg.shell.custom_stl_a, cfg.shell.custom_stl_b)
                if path
            }
            for label, (path_a, path_b) in self._shell_pair_by_label.items():
                available = {
                    os.path.normcase(os.path.abspath(path_a)),
                    os.path.normcase(os.path.abspath(path_b)),
                }
                if wanted == available:
                    matching_label = label
                    break
        if matching_label:
            self.shell_pair_var.set(matching_label)
            self.shell_mode_var.set('custom')
        else:
            self.shell_mode_var.set('auto')

        self._toggle_shell()
        self._redraw_previews()

    def _on_material_changed(self):
        """Load the standard resistivity for a selected material."""
        resistivity = CONDUCTOR_MATERIAL_RESISTIVITY.get(self.material_var.get())
        if resistivity is not None:
            self.resistivity_var.set(f'{resistivity:.3g}')

    def _apply_material(self, cfg: Config) -> None:
        resistivity = float(self.resistivity_var.get())
        if not math.isfinite(resistivity) or resistivity <= 0:
            raise ValueError(self.root.tr("Resistivity must be a positive number."))
        cfg.fasthenry.material = self.material_var.get()
        cfg.fasthenry.specific_conductivity = resistivity

    def _apply_wire_geometry(self, cfg: Config) -> None:
        diameter = mm_to_m(self.cw_var.get())
        groove_height = mm_to_m(self.a_var.get())
        groove_width = mm_to_m(self.b_var.get())
        if diameter <= 0 or groove_height <= 0 or groove_width <= 0:
            raise ValueError(self.root.tr(
                "Cable and groove dimensions must be positive."))
        cfg.wire.conductor_width = diameter
        cfg.wire.cross_section_a_frac = groove_height / diameter
        cfg.wire.cross_section_b_frac = groove_width / diameter

    def _toggle_roi(self):
        """Show single R or independent Rx/Ry/Rz according to the checkbox."""
        if self.roi_ellipsoidal_var.get():
            # Seed from the current spherical R whenever enabling ellipsoidal mode.
            r = self.roi_var.get().strip()
            if r:
                self.roi_rx_var.set(r)
                self.roi_ry_var.set(r)
                self.roi_rz_var.set(r)
            self.roi_sphere_frame.grid_remove()
            self.roi_ellip_frame.grid()
        else:
            self.roi_ellip_frame.grid_remove()
            self.roi_sphere_frame.grid()
        if hasattr(self, 'geo3d_ax') and hasattr(self, 'cyl_ax'):
            self._redraw_previews()

    def _selected_shell_pair(self) -> Optional[Tuple[str, str]]:
        label = self.shell_pair_var.get().strip()
        if not label:
            return None
        return self._shell_pair_by_label.get(label)

    def _on_shell_pair_changed(self):
        self._update_measured_dims_label()
        if hasattr(self, 'geo3d_ax') and hasattr(self, 'cyl_ax'):
            self._redraw_previews()

    def _update_measured_dims_label(self):
        pair = self._selected_shell_pair()
        if pair is None:
            self.dims_readonly_var.set(self.root.tr(
                "No STL pairs in assets/shells (g_Na.stl + g_Nb.stl)"))
            return
        try:
            cfg = Config(show_plots=False)
            dims = apply_custom_shell_dims(cfg, pair[0], pair[1])
            r_ext = dims['outer_r_m'] * 1000.0
            r_int = dims['inner_r_m'] * 1000.0
            height = dims['axial_length_m'] * 1000.0
            self.dims_readonly_var.set(self.root.tr(
                "From STL: Rext {outer:.2f} mm  |  Rint {inner:.2f} mm  |  Height {height:.1f} mm",
                outer=r_ext, inner=r_int, height=height))
        except Exception as exc:
            self.dims_readonly_var.set(self.root.tr(
                "Could not measure the STL: {error}", error=exc))

    def _toggle_shell(self):
        custom = self.shell_mode_var.get() == 'custom'
        if custom:
            self.radius_label.grid_remove()
            self.radius_entry.grid_remove()
            self.height_label.grid_remove()
            self.height_entry.grid_remove()
            self.dims_readonly_label.grid(row=1, column=0, columnspan=4,
                                          sticky='w', padx=4, pady=4)
            self.shell_pair_label.grid(row=9, column=0, sticky='w', padx=4, pady=2)
            self.shell_pair_combo.grid(row=9, column=1, columnspan=2, sticky='w', padx=4)
            self.margin_label.grid_remove()
            self.margin_entry.grid_remove()
            self._update_measured_dims_label()
        else:
            self.dims_readonly_label.grid_remove()
            self.radius_label.grid()
            self.radius_entry.grid()
            self.height_label.grid()
            self.height_entry.grid()
            self.shell_pair_label.grid_remove()
            self.shell_pair_combo.grid_remove()
            self.margin_label.grid()
            self.margin_entry.grid()
            self.margin_entry.configure(state='normal')
        if hasattr(self, 'geo3d_ax') and hasattr(self, 'cyl_ax'):
            self._redraw_previews()

    def _preview_cfg(self) -> Config:
        cfg = Config(gradient_axis=self.axis_var.get(), show_plots=False)
        self._apply_wire_geometry(cfg)
        cfg.wire.cross_section_n = int(self.n_var.get())
        self._apply_material(cfg)
        cfg.shell.auto_margin_pct = float(self.margin_var.get()) / 100.0
        cfg.winding.layer_gap_mm = mm_to_m(self.layer_gap_var.get())
        cfg.winding.normal_shift = None
        if self.roi_ellipsoidal_var.get():
            cfg.target.rx = mm_to_m(self.roi_rx_var.get())
            cfg.target.ry = mm_to_m(self.roi_ry_var.get())
            cfg.target.rz = mm_to_m(self.roi_rz_var.get())
        else:
            r = mm_to_m(self.roi_var.get())
            cfg.target.rx = cfg.target.ry = cfg.target.rz = r
        if self.shell_mode_var.get() == 'custom':
            pair = self._selected_shell_pair()
            if pair is not None:
                apply_custom_shell_dims(cfg, pair[0], pair[1])
            else:
                cfg.cylinder.radius = mm_to_m(self.radius_var.get())
                cfg.cylinder.height = mm_to_m(self.height_var.get())
        else:
            cfg.cylinder.radius = mm_to_m(self.radius_var.get())
            cfg.cylinder.height = mm_to_m(self.height_var.get())
        return cfg

    def _redraw_previews(self):
        self._redraw_cylinder_preview()
        self._redraw_geo3d_preview()

    def _cyl_figure_setup(self, parent: ttk.LabelFrame):
        """Embed a Matplotlib figure for the radial shell preview (square)."""
        holder = _AspectFrame(parent, aspect=1.0)
        holder.pack(fill='both', expand=True, padx=2, pady=2)
        self.cyl_fig = Figure(figsize=(4.0, 4.0), dpi=100, facecolor='white')
        self.cyl_fig.subplots_adjust(left=0.04, right=0.96, bottom=0.04, top=0.96)
        self.cyl_ax = self.cyl_fig.add_subplot(111)
        self.cyl_ax.set_aspect('equal')
        self.cyl_ax.axis('off')
        self.cyl_mpl_canvas = FigureCanvasTkAgg(self.cyl_fig, master=holder.inner)
        self.cyl_mpl_canvas.get_tk_widget().pack(fill='both', expand=True)

    def _geo3d_figure_setup(self, parent: ttk.LabelFrame):
        """Embed a Matplotlib 3D figure for shell + ROI (square canvas)."""
        holder = _AspectFrame(parent, aspect=1.0)
        holder.pack(fill='both', expand=True, padx=2, pady=2)
        self.geo3d_fig = Figure(figsize=(4.0, 4.0), dpi=100, facecolor='white')
        self.geo3d_fig.subplots_adjust(left=0.02, right=0.98, bottom=0.02, top=0.90)
        self.geo3d_ax = self.geo3d_fig.add_subplot(111, projection='3d')
        self.geo3d_mpl_canvas = FigureCanvasTkAgg(self.geo3d_fig, master=holder.inner)
        self.geo3d_mpl_canvas.get_tk_widget().pack(fill='both', expand=True)
        self.geo3d_alert_lbl = ttk.Label(
            parent, text="", foreground='#b71c1c', wraplength=280, justify='left')
        self.geo3d_alert_lbl.pack(fill='x', padx=4, pady=(0, 2))
        # Keep wraplength roughly matched to the pane width.
        parent.bind(
            '<Configure>',
            lambda e: self.geo3d_alert_lbl.configure(
                wraplength=max(120, e.width - 16)),
        )

    def _geo3d_show_message(self, text: str, color: str = '#aa0000'):
        ax = self.geo3d_ax
        ax.clear()
        ax.set_axis_off()
        ax.text2D(0.5, 0.5, text, ha='center', va='center', color=color,
                  fontsize=10, transform=ax.transAxes)
        if hasattr(self, 'geo3d_alert_lbl'):
            self.geo3d_alert_lbl.config(text='')
        self.geo3d_mpl_canvas.draw_idle()

    @staticmethod
    def _set_axes_equal_3d(ax, lim: float):
        """Force a cubic bounding box so the cylinder/ROI are not stretched."""
        ax.set_xlim(-lim, lim)
        ax.set_ylim(-lim, lim)
        ax.set_zlim(-lim, lim)
        try:
            ax.set_box_aspect((1, 1, 1))
        except AttributeError:
            pass

    @staticmethod
    def _roi_cylinder_collision(rx: float, ry: float, rz: float,
                                r_inner: float, half_h: float) -> list:
        """Return human-readable reasons why the ROI is outside the bore.

        The ROI must lie inside the hollow bore (radius ``r_inner``,
        |z| <= ``half_h``). An axis-aligned ellipsoid centered at the origin
        fits iff max(Rx, Ry) <= R_int and Rz <= H/2.
        """
        reasons = []
        rho_max = max(rx, ry)
        if rho_max > r_inner + 1e-12:
            reasons.append(
                f"ROI radial (max Rx/Ry={rho_max*1000:.1f} mm) > "
                f"R_int={r_inner*1000:.1f} mm")
        if rz > half_h + 1e-12:
            reasons.append(
                f"ROI axial (Rz={rz*1000:.1f} mm) > "
                f"H/2={half_h*1000:.1f} mm")
        return reasons

    def _redraw_geo3d_preview(self):
        """3D hollow cylinder (R_int / R_ext / height) + ROI ellipsoid (Rx, Ry, Rz).

        Physical frame: bore along +Z, ROI along X/Y/Z = Rx/Ry/Rz.
        Display remap plots (X, Z, Y) so matplotlib's vertical axis is Y.
        """
        try:
            cfg = self._preview_cfg()
        except ValueError:
            self._geo3d_show_message(self.root.tr("Invalid input"))
            return

        r_outer = cfg.shell_outer_radius
        r_inner = cfg.shell_inner_radius
        height = cfg.cylinder.height
        rx, ry, rz = cfg.target.rx, cfg.target.ry, cfg.target.rz

        if (r_outer <= 0 or r_inner <= 0 or r_inner >= r_outer
                or height <= 0 or rx <= 0 or ry <= 0 or rz <= 0):
            self._geo3d_show_message(self.root.tr("Invalid geometry"))
            return

        ax = self.geo3d_ax
        ax.clear()

        half_h = 0.5 * height
        collision = self._roi_cylinder_collision(rx, ry, rz, r_inner, half_h)
        # Plot in mm so axis ticks match the GUI units.
        scale = 1000.0
        r_outer_mm = r_outer * scale
        r_inner_mm = r_inner * scale
        half_h_mm = half_h * scale
        rx_mm, ry_mm, rz_mm = rx * scale, ry * scale, rz * scale

        n_th = 48
        n_z = 12
        theta = np.linspace(0.0, 2.0 * math.pi, n_th)
        zs = np.linspace(-half_h_mm, half_h_mm, n_z)
        Theta, Z = np.meshgrid(theta, zs)

        # Outer / inner cylindrical walls (physical axis along +Z).
        # Display as (X, Z, Y) so Y is the vertical screen axis.
        Xo = r_outer_mm * np.cos(Theta)
        Yo = r_outer_mm * np.sin(Theta)
        Xi = r_inner_mm * np.cos(Theta)
        Yi = r_inner_mm * np.sin(Theta)
        ax.plot_surface(Xo, Z, Yo, color='#9aa3ad', alpha=0.28,
                        linewidth=0, antialiased=True, shade=True)
        ax.plot_surface(Xi, Z, Yi, color='#c5cdd6', alpha=0.22,
                        linewidth=0, antialiased=True, shade=True)

        # Annular end caps at physical z = ±height/2.
        rr = np.linspace(r_inner_mm, r_outer_mm, 8)
        Theta_c, R_c = np.meshgrid(theta, rr)
        Xc = R_c * np.cos(Theta_c)
        Yc = R_c * np.sin(Theta_c)
        for z_cap in (-half_h_mm, half_h_mm):
            ax.plot_surface(Xc, np.full_like(Xc, z_cap), Yc,
                            color='#7a8490', alpha=0.35, linewidth=0,
                            antialiased=True, shade=True)

        # Outline rings to clarify the bore.
        th = np.linspace(0.0, 2.0 * math.pi, 80)
        for r in (r_inner_mm, r_outer_mm):
            x_ring = r * np.cos(th)
            y_ring = r * np.sin(th)
            for z_ring in (-half_h_mm, half_h_mm):
                ax.plot(x_ring, np.full_like(th, z_ring), y_ring,
                        color='#333333', lw=0.9, alpha=0.85)

        # ROI ellipsoid: blue if inside bore, red if colliding / outside.
        u = np.linspace(0.0, 2.0 * math.pi, 36)
        v = np.linspace(0.0, math.pi, 20)
        xe = rx_mm * np.outer(np.cos(u), np.sin(v))
        ye = ry_mm * np.outer(np.sin(u), np.sin(v))
        ze = rz_mm * np.outer(np.ones_like(u), np.cos(v))
        roi_color = '#e53935' if collision else '#2f80ed'
        ax.plot_surface(xe, ze, ye, color=roi_color, alpha=0.50,
                        linewidth=0, antialiased=True, shade=True)

        lim = max(half_h_mm, r_outer_mm, rx_mm, ry_mm, rz_mm) * 1.15
        self._set_axes_equal_3d(ax, lim)
        ax.set_xlabel('X [mm]', fontsize=7, labelpad=-2)
        ax.set_ylabel('Z [mm]', fontsize=7, labelpad=-2)
        ax.set_zlabel('Y [mm]', fontsize=7, labelpad=-2)
        ax.tick_params(labelsize=6, pad=-2)
        ax.view_init(elev=18, azim=-60)

        title = (
            f"Rint={r_inner*1000:.1f}  Rext={r_outer*1000:.1f}  H={height*1000:.0f} mm\n"
            f"ROI  Rx={rx*1000:.1f}  Ry={ry*1000:.1f}  Rz={rz*1000:.1f} mm"
        )
        if collision:
            title += "\n⚠ " + self.root.tr("ROI outside / colliding with shell")
            ax.set_title(title, fontsize=7.5, pad=4, color='#b71c1c')
            if hasattr(self, 'geo3d_alert_lbl'):
                self.geo3d_alert_lbl.config(
                    text=self.root.tr("Alert: {details}", details="; ".join(collision)),
                    foreground='#b71c1c')
        else:
            ax.set_title(title, fontsize=7.5, pad=4, color='#222222')
            if hasattr(self, 'geo3d_alert_lbl'):
                self.geo3d_alert_lbl.config(
                    text=self.root.tr("ROI inside bore (no collision)"),
                    foreground='#2e7d32')
        self.geo3d_mpl_canvas.draw_idle()

    @staticmethod
    def _annular_sector_poly(r_in: float, r_out: float,
                             t0: float, t1: float, n: int = 72) -> np.ndarray:
        """Closed polygon for an annular sector (angles in radians, CCW from +x)."""
        ts_out = np.linspace(t0, t1, n)
        ts_in = np.linspace(t1, t0, n)
        x = np.concatenate([r_out * np.cos(ts_out), r_in * np.cos(ts_in)])
        y = np.concatenate([r_out * np.sin(ts_out), r_in * np.sin(ts_in)])
        return np.column_stack([x, y])

    @staticmethod
    def _radial_ellipse_polys(
        center_radius: float,
        theta: float,
        semi_radial: float,
        semi_tangent: float,
        peel_toward: str,
        peel_frac: float,
        n: int = 48,
    ) -> Tuple[np.ndarray, np.ndarray, np.ndarray]:
        """Return (kept, peel, outline) polygons for a radially aligned groove ellipse.

        ``peel_toward`` is ``'out'`` (toward +radial / R_ext) or ``'in'``
        (toward -radial / R_int). ``peel_frac`` is ``auto_margin_pct`` in [0, 1].
        """
        peel_frac = float(np.clip(peel_frac, 0.0, 1.0))
        rux, ruy = math.cos(theta), math.sin(theta)
        tux, tuy = -math.sin(theta), math.cos(theta)
        gx = center_radius * rux
        gy = center_radius * ruy

        def _xy(lr: float, lt: float) -> Tuple[float, float]:
            return (gx + lr * rux + lt * tux, gy + lr * ruy + lt * tuy)

        def _on_ellipse(a: float) -> Tuple[float, float]:
            return _xy(semi_radial * math.cos(a), semi_tangent * math.sin(a))

        outline = np.asarray(
            [_on_ellipse(2.0 * math.pi * i / n) for i in range(n)], dtype=float)

        # Peel depth along local radial from the free-surface tip.
        peel = 2.0 * peel_frac * semi_radial
        if peel < 1e-15 or semi_radial <= 0:
            return outline.copy(), np.empty((0, 2)), outline

        if peel_toward == 'out':
            # Peel occupies lr in (split, +semi]; split = semi - peel.
            split = semi_radial - peel
            split = float(np.clip(split, -semi_radial, semi_radial))
            a0 = math.acos(float(np.clip(split / semi_radial, -1.0, 1.0)))
            # Outer tip: a in [-a0, +a0] (cos large / outward).
            peel_poly = np.asarray(
                [_on_ellipse(a) for a in np.linspace(-a0, a0, max(n // 2, 8))],
                dtype=float)
            # Kept: complementary arc a in [a0, 2pi - a0].
            kept_poly = np.asarray(
                [_on_ellipse(a) for a in np.linspace(a0, 2.0 * math.pi - a0,
                                                     max(n, 16))],
                dtype=float)
        else:
            # Peel occupies lr in [-semi, split); split = -semi + peel.
            split = -semi_radial + peel
            split = float(np.clip(split, -semi_radial, semi_radial))
            a0 = math.acos(float(np.clip(split / semi_radial, -1.0, 1.0)))
            # Inner tip: a in [a0, 2pi - a0] (cos small / inward).
            peel_poly = np.asarray(
                [_on_ellipse(a) for a in np.linspace(a0, 2.0 * math.pi - a0,
                                                     max(n // 2, 8))],
                dtype=float)
            # Kept: complementary outer-ish arc a in [-a0, +a0].
            kept_poly = np.asarray(
                [_on_ellipse(a) for a in np.linspace(-a0, a0, max(n, 16))],
                dtype=float)

        return kept_poly, peel_poly, outline

    def _cyl_show_message(self, text: str, color: str = '#aa0000'):
        ax = self.cyl_ax
        ax.clear()
        ax.set_aspect('equal')
        ax.axis('off')
        ax.set_xlim(0, 1)
        ax.set_ylim(0, 1)
        ax.text(0.5, 0.5, text, ha='center', va='center', color=color,
                fontsize=10, transform=ax.transAxes)
        self.cyl_mpl_canvas.draw_idle()

    def _redraw_cylinder_preview(self):
        """Zoomed quadrant of the shell wall with layers, gap, and grooves."""
        try:
            cfg = self._preview_cfg()
        except ValueError:
            self._cyl_show_message(self.root.tr("Invalid input"))
            return

        r_outer = cfg.shell_outer_radius
        r_inner = cfg.shell_inner_radius
        design_r = cfg.cylinder_design_radius
        peel = cfg.radial_peel
        h = cfg.cable_height
        gap = cfg.layer_crossing_gap
        wall = cfg.shell_wall_thickness
        margin_pct = cfg.shell.auto_margin_pct
        shift = cfg.normal_shift_length
        inner_layer_r = design_r + shift
        semi_a = cfg.conductor_semi_a
        semi_b = cfg.conductor_semi_b

        degenerate = (r_outer <= 0 or r_inner <= 0 or design_r <= 0
                      or wall <= 0 or r_inner >= r_outer or h <= 0)
        if degenerate:
            self._cyl_show_message(self.root.tr("Invalid geometry"))
            return

        ax = self.cyl_ax
        ax.clear()
        ax.set_aspect('equal')
        ax.axis('off')

        # Angular FOV and groove spacing lock to the physical arc lengths that
        # look good at R_ref = 0.04 m (~74° sector, grooves ~20° apart).
        # Larger R → proportionally narrower angles so wall/cables keep size.
        r_ref = 0.04
        theta_mid = math.radians(45.0)
        theta_span_ref = math.radians(74.0)   # was 8°..82°
        theta_sep_ref = math.radians(20.0)    # was 35° and 55°
        mid_r = max(0.5 * (r_inner + r_outer), 1e-6)
        arc_span_ref = r_ref * theta_span_ref
        arc_sep_ref = r_ref * theta_sep_ref
        theta_span = arc_span_ref / mid_r
        theta_sep = arc_sep_ref / mid_r
        # Only cap the upper angle (small cylinders); never inflate separation.
        theta_span = min(theta_span, math.radians(85.0))
        theta_sep = min(theta_sep, 0.55 * theta_span)
        t0 = theta_mid - 0.5 * theta_span
        t1 = theta_mid + 0.5 * theta_span
        th_outer = theta_mid - 0.5 * theta_sep
        th_inner = theta_mid + 0.5 * theta_sep

        layer_keep = max(h - peel, 0.0)  # radial thickness of each gray band

        r_outer_inner = r_outer - layer_keep          # inner edge of outer gray
        r_inner_outer = r_inner + layer_keep          # outer edge of inner gray
        # Gap band between the two gray layers (may be ~0).
        gap_hi = r_outer_inner
        gap_lo = r_inner_outer

        # --- Wall layers ---
        gray = '#c5c5c5'
        gray_edge = '#555555'
        blue_gap = '#b7dff5'
        blue_edge = '#3a7ca5'

        outer_poly = self._annular_sector_poly(r_outer_inner, r_outer, t0, t1)
        ax.add_patch(Polygon(outer_poly, closed=True, facecolor=gray,
                             edgecolor=gray_edge, linewidth=1.0, zorder=1))

        if gap_hi - gap_lo > 1e-9:
            gap_poly = self._annular_sector_poly(gap_lo, gap_hi, t0, t1)
            ax.add_patch(Polygon(gap_poly, closed=True, facecolor=blue_gap,
                                 edgecolor=blue_edge, linewidth=0.8, zorder=1))
        elif gap > 0:
            # Degenerate thin gap: draw a mid-arc line.
            ts = np.linspace(t0, t1, 48)
            r_mid = 0.5 * (gap_lo + gap_hi)
            ax.plot(r_mid * np.cos(ts), r_mid * np.sin(ts),
                    color=blue_edge, lw=1.2, zorder=2)

        inner_poly = self._annular_sector_poly(r_inner, r_inner_outer, t0, t1)
        ax.add_patch(Polygon(inner_poly, closed=True, facecolor=gray,
                             edgecolor=gray_edge, linewidth=1.0, zorder=1))

        # Outer / inner bore outlines (emphasize shell faces).
        ts = np.linspace(t0, t1, 64)
        ax.plot(r_outer * np.cos(ts), r_outer * np.sin(ts),
                color='#111111', lw=1.6, zorder=3)
        ax.plot(r_inner * np.cos(ts), r_inner * np.sin(ts),
                color='#111111', lw=1.6, zorder=3)

        # --- Grooves (radially oriented ellipses, peel-split) ---
        kept_color = '#7dcf8a'
        peel_color = '#e57373'
        groove_edge = '#5a3a00'
        groove_specs = (
            (design_r, th_outer, 'out'),      # capa exterior
            (inner_layer_r, th_inner, 'in'),  # capa interior
        )
        for center_r, th, peel_dir in groove_specs:
            if center_r <= 0:
                continue
            kept_poly, peel_poly, outline = self._radial_ellipse_polys(
                center_r, th, semi_a, semi_b, peel_dir, margin_pct)
            if len(kept_poly) >= 3:
                ax.add_patch(Polygon(kept_poly, closed=True,
                                     facecolor=kept_color, edgecolor='none',
                                     alpha=0.95, zorder=4))
            if len(peel_poly) >= 3 and margin_pct > 1e-6:
                ax.add_patch(Polygon(peel_poly, closed=True,
                                     facecolor=peel_color, edgecolor='none',
                                     alpha=0.95, zorder=4))
            if len(outline) >= 3:
                ax.add_patch(Polygon(outline, closed=True,
                                     facecolor='none', edgecolor=groove_edge,
                                     linewidth=1.2, zorder=5))

        # --- Zoom on geometry only; labels use axes-fraction (never clipped) ---
        def _pt(r, th):
            return r * math.cos(th), r * math.sin(th)

        geom_pad = max(0.18 * wall, 2.5 * semi_a, 1e-4)
        pts = []
        for r in (r_inner, r_outer):
            for th in (t0, t1, theta_mid):
                pts.append(_pt(r, th))
        for center_r, th, _ in groove_specs:
            if center_r > 0:
                pts.append(_pt(center_r + semi_a, th))
                pts.append(_pt(max(center_r - semi_a, 0.0), th))
                pts.append((
                    center_r * math.cos(th) - semi_b * math.sin(th),
                    center_r * math.sin(th) + semi_b * math.cos(th),
                ))
                pts.append((
                    center_r * math.cos(th) + semi_b * math.sin(th),
                    center_r * math.sin(th) - semi_b * math.cos(th),
                ))
        xs = [p[0] for p in pts]
        ys = [p[1] for p in pts]
        x0, x1 = min(xs) - geom_pad, max(xs) + geom_pad
        y0, y1 = min(ys) - geom_pad, max(ys) + geom_pad
        # Extra room on left/bottom/right for the floating labels' arrows.
        span = max(x1 - x0, y1 - y0, arc_span_ref * 0.75)
        mid_r_pt = _pt(mid_r, theta_mid)
        # Bias center slightly so shell sits mid-right; labels occupy margins.
        cxv = mid_r_pt[0] + 0.02 * span
        cyv = mid_r_pt[1] + 0.02 * span
        ax.set_xlim(cxv - 0.55 * span, cxv + 0.45 * span)
        ax.set_ylim(cyv - 0.52 * span, cyv + 0.48 * span)

        spoke = t0 + 0.10 * theta_span
        p_ext = _pt(r_outer, spoke)
        p_int = _pt(r_inner, spoke)
        r_gap = 0.5 * (gap_lo + gap_hi) if (gap_hi - gap_lo) > 1e-12 else mid_r
        p_gap = _pt(r_gap, theta_mid)
        th_wall = t1 - 0.12 * theta_span
        p_w0 = _pt(r_inner, th_wall)
        p_w1 = _pt(r_outer, th_wall)
        mid_w = (0.5 * (p_w0[0] + p_w1[0]), 0.5 * (p_w0[1] + p_w1[1]))
        r_peel_pt = design_r + max(semi_a - 0.5 * peel, 0.25 * semi_a)
        p_peel = _pt(r_peel_pt, th_outer)

        arrow = dict(arrowstyle='->', lw=0.8, shrinkA=0, shrinkB=2)
        # Labels in axes fraction → always inside the plot frame.
        ax.annotate(
            f"$R_{{int}}$ = {r_inner*1000:.1f} mm",
            xy=p_int, xycoords='data',
            xytext=(0.04, 0.44), textcoords='axes fraction',
            fontsize=7.5, color='#111111', ha='left', va='center',
            arrowprops=dict(color='#111111', **arrow),
            zorder=6, clip_on=False,
        )
        ax.annotate(
            f"$R_{{ext}}$ = {r_outer*1000:.1f} mm",
            xy=p_ext, xycoords='data',
            xytext=(0.04, 0.30), textcoords='axes fraction',
            fontsize=7.5, color='#111111', ha='left', va='center',
            arrowprops=dict(color='#111111', **arrow),
            zorder=6, clip_on=False,
        )
        ax.annotate(
            f"Gap: {gap*1000:.2f} mm",
            xy=p_gap, xycoords='data',
            xytext=(0.55, 0.90), textcoords='axes fraction',
            fontsize=7.5, color='#1a5f7a', ha='center', va='top',
            arrowprops=dict(color='#1a5f7a', **arrow),
            zorder=6, clip_on=False,
        )
        ax.annotate(
            self.root.tr("Thickness: {value:.2f} mm", value=wall * 1000),
            xy=mid_w, xycoords='data',
            xytext=(0.22, 0.90), textcoords='axes fraction',
            fontsize=7.5, color='#333333', ha='center', va='top',
            arrowprops=dict(color='#333333', **arrow),
            zorder=6, clip_on=False,
        )
        ax.annotate(
            self.root.tr("Trim: {value:.0f}%", value=margin_pct * 100),
            xy=p_peel, xycoords='data',
            xytext=(0.90, 0.70), textcoords='axes fraction',
            fontsize=7.5, color='#b71c1c', ha='right', va='center',
            arrowprops=dict(color='#b71c1c', **arrow),
            zorder=6, clip_on=False,
        )
        ax.annotate(
            '', xy=p_w1, xytext=p_w0,
            arrowprops=dict(arrowstyle='<->', color='#333333', lw=0.9),
            zorder=6,
        )

        self.cyl_mpl_canvas.draw_idle()

    def _build_cfg(self) -> Config:
        cfg = Config(
            gradient_axis=self.axis_var.get(),
            tikhonov_factor=float(self.tikhonov_var.get()),
            num_levels=int(self.levels_var.get()),
            show_plots=False,
            overlap_warn=self.overlap_var.get(),
        )
        if self.roi_ellipsoidal_var.get():
            cfg.target.rx = mm_to_m(self.roi_rx_var.get())
            cfg.target.ry = mm_to_m(self.roi_ry_var.get())
            cfg.target.rz = mm_to_m(self.roi_rz_var.get())
        else:
            r = mm_to_m(self.roi_var.get())
            cfg.target.rx = cfg.target.ry = cfg.target.rz = r
        self._apply_wire_geometry(cfg)
        cfg.wire.cross_section_n = int(self.n_var.get())
        self._apply_material(cfg)
        cfg.shell.shell_outer_pad = max(0.0005, 0.65 * cfg.conductor_semi_a)
        try:
            cfg.winding.layer_gap_mm = mm_to_m(self.layer_gap_var.get())
            cfg.winding.normal_shift = None
        except ValueError:
            pass
        cfg.control.run_gradient = self.run_gradient_var.get()
        cfg.control.run_leads = self.run_leads_var.get()
        cfg.control.run_shell = self.run_shell_var.get()
        if self.shell_mode_var.get() == 'custom':
            pair = self._selected_shell_pair()
            if pair is None:
                raise ValueError(self.root.tr(
                    "No STL pair is selected. Place g_Na.stl / g_Nb.stl halves in assets/shells."))
            apply_custom_shell_dims(cfg, pair[0], pair[1])
        else:
            cfg.cylinder.radius = mm_to_m(self.radius_var.get())
            cfg.cylinder.height = mm_to_m(self.height_var.get())
            # Autogenerated hollow cylinder: editable margin (% of cable height).
            if hasattr(self, 'margin_var'):
                try:
                    cfg.shell.auto_margin_pct = float(self.margin_var.get()) / 100.0
                except ValueError:
                    pass
        if cfg.cylinder.radius <= 0 or cfg.cylinder_design_radius <= 0:
            raise ValueError(self.root.tr(
                "The cylinder outer radius must be greater than cable semi-axis A."))
        if (not cfg.shell.use_custom_stl
                and cfg.estimated_shell_thickness <= 0):
            raise ValueError(self.root.tr(
                "The radius, cable height, and layer gap leave the autogenerated cylinder with no usable radial thickness."))
        if (cfg.shell.use_custom_stl
                and cfg.shell_inner_radius >= cfg.shell_outer_radius):
            raise ValueError(self.root.tr(
                "The custom STL has Rint >= Rext; check the halves in assets/shells."))
        # Advanced leads knobs (optional; only override if shown & valid).
        if getattr(self, 'adv_visible', None) and self.adv_visible.get():
            try:
                cfg.leads.lead_blend = mm_to_m(self.lead_blend_var.get())
            except ValueError:
                pass
            try:
                cfg.leads.cs_blend_rings = int(self.cs_blend_rings_var.get())
            except ValueError:
                pass
            try:
                cfg.leads.junction_rigid_steps = int(self.junction_rigid_steps_var.get())
            except ValueError:
                pass
        return cfg

    def _ask_user(self, question: str) -> bool:
        """Runs on the main thread via root.after; returns user's accept/reject."""
        return messagebox.askyesno(
            self.root.tr("Cable collision"),
            question,
            icon=messagebox.WARNING,
            default=messagebox.NO,
            parent=self.root,
        )

    def _set_running(self, running: bool):
        self.run_btn.configure(state='disabled' if running else 'normal')
        if running:
            self.stop_btn.configure(state='normal', text=self.root.tr("Stop"))
            if not self.stop_btn.winfo_ismapped():
                self.stop_btn.pack(side='left', padx=(6, 0), before=self.progress)
        else:
            if self.stop_btn.winfo_ismapped():
                self.stop_btn.pack_forget()

    def _on_stop(self):
        if self.runner is not None:
            self.runner.request_stop()
        self.stop_btn.configure(state='disabled', text=self.root.tr("Stopping..."))

    def _on_run(self):
        out_dir = self.get_output_dir()
        if not out_dir:
            messagebox.showwarning(self.root.tr("Missing directory"),
                                   self.root.tr("Select an output directory first."))
            return
        try:
            cfg = self._build_cfg()
        except (ValueError, KeyError) as exc:
            messagebox.showerror(self.root.tr("Invalid parameters"), str(exc))
            return
        cfg.output_dir = out_dir
        question_language = self.root.language_var.get()
        self._set_running(True)

        # The overlap check happens inside run_gradient. We hand the runner's
        # ask_user through so a popup appears when collisions are detected.
        def _target(ask_user=None):
            from run_pipeline import run_pipeline as _run
            return _run(cfg, should_stop=self.runner.should_stop,
                        ask_user=ask_user,
                        question_language=question_language)

        def _on_done(result, err):
            self._set_running(False)
            if err is not None:
                messagebox.showerror(
                    "Pipeline", self.root.tr("Failed: {error}", error=err))
            elif getattr(result, 'discarded', False):
                messagebox.showwarning(
                    self.root.tr("Result discarded"),
                    self.root.tr(
                        "The result was discarded, so leads and shell were not run.\n\nThe cable generated by pyCoilGen was kept for diagnosis at:\n{path}",
                        path=result.output_dir),
                )
            else:
                output_dir = getattr(result, 'output_dir', result)
                messagebox.showinfo(
                    "Pipeline", self.root.tr("Done.\nResults in:\n{path}", path=output_dir))

        self.runner.run(_target, on_done=_on_done, ask_user=self._ask_user)

    def retranslate(self):
        """Refresh dynamic preview text after a language change."""
        self._update_measured_dims_label()
        if hasattr(self, 'geo3d_ax'):
            self._redraw_previews()
