"""
Pipeline panel — full gradient + leads + shell run.

Lets the user pick the gradient axis, dimensions, Tikhonov, levels, wire
characteristics, and whether to carve into a custom STL or the autogenerated
cylinder / Fusion shell halves. Runs the three steps in a worker thread and
surfaces the wire-overlap report as an accept/reject popup.
"""

from __future__ import annotations

import os
import tkinter as tk
from tkinter import filedialog, messagebox, ttk
from typing import Optional

from coilgen.config import Config
from .runner import WorkerRunner


class PipelinePanel(ttk.Frame):
    def __init__(self, master, get_output_dir, set_output_dir, root):
        super().__init__(master)
        self.get_output_dir = get_output_dir
        self.set_output_dir = set_output_dir
        self.root = root
        self.runner: Optional[WorkerRunner] = None

        self._build()

    def _build(self):
        body = ttk.PanedWindow(self, orient='horizontal')
        body.pack(fill='both', expand=True, padx=8, pady=6)

        left = ttk.Frame(body)
        body.add(left, weight=3)

        form = ttk.LabelFrame(left, text="Pipeline completo", padding=10)
        form.pack(fill='x', pady=(0, 6))

        # Axis
        ttk.Label(form, text="Eje gradiente:").grid(row=0, column=0, sticky='w', padx=4, pady=4)
        self.axis_var = tk.StringVar(value='y')
        ttk.Combobox(form, textvariable=self.axis_var, values=['x', 'y', 'z'],
                     state='readonly', width=6).grid(row=0, column=1, sticky='w')

        # Dimensions
        ttk.Label(form, text="Radio cilindro [m]:").grid(row=1, column=0, sticky='w', padx=4, pady=4)
        self.radius_var = tk.StringVar(value='0.150')
        ttk.Entry(form, textvariable=self.radius_var, width=10).grid(row=1, column=1, sticky='w')
        ttk.Label(form, text="Altura cilindro [m]:").grid(row=1, column=2, sticky='w', padx=4)
        self.height_var = tk.StringVar(value='0.430')
        ttk.Entry(form, textvariable=self.height_var, width=10).grid(row=1, column=3, sticky='w')
        ttk.Label(form, text="Radio ROI [m]:").grid(row=2, column=0, sticky='w', padx=4, pady=4)
        self.roi_var = tk.StringVar(value='0.125')
        ttk.Entry(form, textvariable=self.roi_var, width=10).grid(row=2, column=1, sticky='w')

        # Optimization
        ttk.Label(form, text="Tikhonov:").grid(row=3, column=0, sticky='w', padx=4, pady=4)
        self.tikhonov_var = tk.StringVar(value='2500')
        ttk.Entry(form, textvariable=self.tikhonov_var, width=10).grid(row=3, column=1, sticky='w')
        ttk.Label(form, text="Niveles (vueltas):").grid(row=3, column=2, sticky='w', padx=4)
        self.levels_var = tk.StringVar(value='26')
        ttk.Entry(form, textvariable=self.levels_var, width=10).grid(row=3, column=3, sticky='w')

        # Wire characteristics
        ttk.Label(form, text="Ancho conductor [m]:").grid(row=4, column=0, sticky='w', padx=4, pady=4)
        self.cw_var = tk.StringVar(value='0.00225')
        ttk.Entry(form, textvariable=self.cw_var, width=10).grid(row=4, column=1, sticky='w')
        ttk.Label(form, text="Seccion A:").grid(row=4, column=2, sticky='w', padx=4)
        self.a_var = tk.StringVar(value='1.6')
        ttk.Entry(form, textvariable=self.a_var, width=8).grid(row=4, column=3, sticky='w')
        ttk.Label(form, text="Seccion B:").grid(row=5, column=0, sticky='w', padx=4, pady=4)
        self.b_var = tk.StringVar(value='0.7')
        ttk.Entry(form, textvariable=self.b_var, width=8).grid(row=5, column=1, sticky='w')
        ttk.Label(form, text="Seccion N:").grid(row=5, column=2, sticky='w', padx=4)
        self.n_var = tk.StringVar(value='16')
        ttk.Entry(form, textvariable=self.n_var, width=8).grid(row=5, column=3, sticky='w')

        # Custom STL vs autogenerated
        self.shell_mode_var = tk.StringVar(value='auto')  # 'auto' or 'custom'
        ttk.Radiobutton(form, text="Cilindro hueco autogenerado (1 pieza)",
                        variable=self.shell_mode_var, value='auto',
                        command=self._toggle_shell).grid(row=7, column=0, columnspan=2, sticky='w', padx=4, pady=4)
        ttk.Radiobutton(form, text="STL custom para impresion (2 mitades)",
                        variable=self.shell_mode_var, value='custom',
                        command=self._toggle_shell).grid(row=7, column=2, columnspan=2, sticky='w')
        self.custom_a_var = tk.StringVar(value='')
        self.custom_b_var = tk.StringVar(value='')
        ttk.Label(form, text="Mitad A:").grid(row=8, column=0, sticky='w', padx=4, pady=2)
        self.custom_a_entry = ttk.Entry(form, textvariable=self.custom_a_var, width=34)
        self.custom_a_entry.grid(row=8, column=1, columnspan=2, sticky='we', padx=4)
        self.custom_a_btn = ttk.Button(form, text="Examinar...",
                                       command=lambda: self._pick_custom('a'))
        self.custom_a_btn.grid(row=8, column=3, padx=4)
        ttk.Label(form, text="Mitad B:").grid(row=9, column=0, sticky='w', padx=4, pady=2)
        self.custom_b_entry = ttk.Entry(form, textvariable=self.custom_b_var, width=34)
        self.custom_b_entry.grid(row=9, column=1, columnspan=2, sticky='we', padx=4)
        self.custom_b_btn = ttk.Button(form, text="Examinar...",
                                       command=lambda: self._pick_custom('b'))
        self.custom_b_btn.grid(row=9, column=3, padx=4)
        # Autogenerated hollow-cylinder margin (% of cable height, per side).
        ttk.Label(form, text="Margen surco (% alto cable):").grid(
            row=10, column=0, sticky='w', padx=4, pady=2)
        self.margin_var = tk.StringVar(value='15')
        self.margin_entry = ttk.Entry(form, textvariable=self.margin_var, width=6)
        self.margin_entry.grid(row=10, column=1, sticky='w')
        self._toggle_shell()

        # Cross-section preview (reactive to conductor_width / A / B / N)
        xsec = ttk.LabelFrame(left, text="Seccion transversal", padding=6)
        xsec.pack(fill='x', pady=4)
        self.xsec_canvas = tk.Canvas(xsec, width=240, height=160,
                                     bg='white', highlightthickness=1,
                                     highlightbackground='#cccccc')
        self.xsec_canvas.pack(side='left', padx=(4, 8))
        info = ttk.Frame(xsec)
        info.pack(side='left', fill='y')
        self.xsec_major_lbl = ttk.Label(info, text="Eje mayor: -")
        self.xsec_major_lbl.pack(anchor='w')
        self.xsec_minor_lbl = ttk.Label(info, text="Eje menor: -")
        self.xsec_minor_lbl.pack(anchor='w')
        self.xsec_n_lbl = ttk.Label(info, text="Vertices: -")
        self.xsec_n_lbl.pack(anchor='w')
        for var in (self.cw_var, self.a_var, self.b_var, self.n_var):
            var.trace_add('write', lambda *_: self._redraw_preview())
        self.xsec_canvas.bind('<Configure>', lambda _e: self._redraw_preview())
        self._redraw_preview()

        # Steps toggles
        steps = ttk.LabelFrame(left, text="Pasos", padding=6)
        steps.pack(fill='x', pady=4)
        self.run_gradient_var = tk.BooleanVar(value=True)
        self.run_leads_var = tk.BooleanVar(value=True)
        self.run_shell_var = tk.BooleanVar(value=True)
        self.overlap_var = tk.BooleanVar(value=True)
        ttk.Checkbutton(steps, text="Gradiente (pyCoilGen)", variable=self.run_gradient_var).pack(side='left', padx=6)
        ttk.Checkbutton(steps, text="Leads", variable=self.run_leads_var).pack(side='left', padx=6)
        ttk.Checkbutton(steps, text="Shell", variable=self.run_shell_var).pack(side='left', padx=6)
        ttk.Checkbutton(steps, text="Alertar colisiones", variable=self.overlap_var).pack(side='left', padx=6)

        # Advanced leads (collapsible)
        self.adv_frame = ttk.LabelFrame(left, text="Leads avanzado", padding=6)
        self.adv_frame.pack(fill='x', pady=4)
        self.adv_visible = tk.BooleanVar(value=False)
        self.adv_toggle = ttk.Checkbutton(
            self.adv_frame, text="Mostrar parametros avanzados de leads",
            variable=self.adv_visible, command=self._toggle_advanced)
        self.adv_toggle.pack(anchor='w')
        self.adv_body = ttk.Frame(self.adv_frame)
        # wire_tangent_run [m]
        ttk.Label(self.adv_body, text="wire_tangent_run [m]:").grid(
            row=0, column=0, sticky='w', padx=4, pady=2)
        self.wire_tangent_run_var = tk.StringVar(value='0.020')
        ttk.Entry(self.adv_body, textvariable=self.wire_tangent_run_var,
                  width=10).grid(row=0, column=1, sticky='w')
        # cs_blend_rings
        ttk.Label(self.adv_body, text="cs_blend_rings:").grid(
            row=0, column=2, sticky='w', padx=8, pady=2)
        self.cs_blend_rings_var = tk.StringVar(value='20')
        ttk.Entry(self.adv_body, textvariable=self.cs_blend_rings_var,
                  width=6).grid(row=0, column=3, sticky='w')
        # junction_rigid_steps
        ttk.Label(self.adv_body, text="junction_rigid_steps:").grid(
            row=0, column=4, sticky='w', padx=8, pady=2)
        self.junction_rigid_steps_var = tk.StringVar(value='4')
        ttk.Entry(self.adv_body, textvariable=self.junction_rigid_steps_var,
                  width=6).grid(row=0, column=5, sticky='w')
        self._toggle_advanced()

        # Run button
        bar = ttk.Frame(left)
        bar.pack(fill='x', pady=4)
        ttk.Button(bar, text="Correr pipeline", command=self._on_run).pack(side='left')
        self.progress = ttk.Progressbar(bar, mode='determinate', maximum=100, length=260)
        self.progress.pack(side='left', padx=10, fill='x', expand=True)

        # Log (right column — always visible beside controls)
        log_frame = ttk.LabelFrame(body, text="Log", padding=4)
        body.add(log_frame, weight=2)
        self.log_text = tk.Text(log_frame, width=42, wrap='word')
        self.log_text.pack(side='left', fill='both', expand=True)
        sb = ttk.Scrollbar(log_frame, command=self.log_text.yview)
        sb.pack(side='right', fill='y')
        self.log_text.configure(yscrollcommand=sb.set)

        self.runner = WorkerRunner(self.log_text, self.progress, self.root)

    def _toggle_advanced(self):
        if self.adv_visible.get():
            self.adv_body.pack(fill='x', padx=4, pady=4)
        else:
            self.adv_body.pack_forget()

    def _toggle_shell(self):
        custom = self.shell_mode_var.get() == 'custom'
        state = 'normal' if custom else 'disabled'
        self.custom_a_entry.configure(state=state)
        self.custom_a_btn.configure(state=state)
        self.custom_b_entry.configure(state=state)
        self.custom_b_btn.configure(state=state)
        # Margin field (added with the auto hollow-cylinder) is enabled only
        # in autogenerated mode.
        margin_state = 'normal' if not custom else 'disabled'
        if hasattr(self, 'margin_entry'):
            self.margin_entry.configure(state=margin_state)

    def _pick_custom(self, half: str):
        path = filedialog.askopenfilename(
            title=f"Seleccionar STL mitad {half.upper()} de shell",
            filetypes=[("STL", "*.stl"), ("All", "*.*")],
        )
        if path:
            if half == 'a':
                self.custom_a_var.set(path)
            else:
                self.custom_b_var.set(path)

    def _redraw_preview(self):
        """Draw the conductor's elliptical cross-section on the preview canvas.

        Parametric profile: x = A*cw*sin(theta), y = B*cw*cos(theta). Rotated
        90° for display so the major axis (A) is vertical, matching the STL.
        """
        c = self.xsec_canvas
        try:
            cw = float(self.cw_var.get())
            a = float(self.a_var.get())
            b = float(self.b_var.get())
            n = int(self.n_var.get())
        except ValueError:
            c.delete('all')
            c.create_text(c.winfo_width() // 2 or 120, 80,
                          text="Entradas invalidas", fill='#aa0000')
            return
        c.delete('all')
        w = max(c.winfo_width(), 60)
        h = max(c.winfo_height(), 60)
        semi_major = a * cw   # A — tall axis in the coil frame
        semi_minor = b * cw   # B — wide axis in the coil frame
        major = 2 * semi_major
        minor = 2 * semi_minor
        self.xsec_major_lbl.config(text=f"Eje mayor (A): {major*1000:.3f} mm")
        self.xsec_minor_lbl.config(text=f"Eje menor (B): {minor*1000:.3f} mm")
        self.xsec_n_lbl.config(text=f"Vertices: {n}")
        if semi_major <= 0 or semi_minor <= 0:
            return
        margin = 22
        avail_w = w - 2 * margin
        avail_h = h - 2 * margin
        # 90° rotation: major vertical, minor horizontal.
        scale = min(avail_w / minor, avail_h / major) if major > 0 and minor > 0 else 0
        if scale <= 0:
            return
        cx, cy = w / 2, h / 2
        rx = semi_minor * scale   # horizontal on canvas
        ry = semi_major * scale   # vertical on canvas
        # Axes
        c.create_line(margin, cy, w - margin, cy, fill='#bbbbbb', dash=(3, 3))
        c.create_line(cx, margin, cx, h - margin, fill='#bbbbbb', dash=(3, 3))
        # Ellipse: swap sin/cos mapping so A aligns with canvas Y.
        import math
        pts = []
        for i in range(n):
            th = 2 * math.pi * i / n
            pts.append(cx + rx * math.cos(th))
            pts.append(cy - ry * math.sin(th))
        if len(pts) >= 6:
            c.create_polygon(*pts, outline='#0066cc', fill='#cfe8ff', width=1.5)
        # Dimension annotations (major vertical, minor horizontal)
        c.create_text(12, cy, angle=90, text=f"{major*1000:.3f} mm", fill='#333333')
        c.create_text(cx, 12, text=f"{minor*1000:.3f} mm", fill='#333333')

    def _build_cfg(self) -> Config:
        cfg = Config(
            gradient_axis=self.axis_var.get(),
            tikhonov_factor=float(self.tikhonov_var.get()),
            num_levels=int(self.levels_var.get()),
            show_plots=False,
            overlap_warn=self.overlap_var.get(),
        )
        cfg.cylinder.radius = float(self.radius_var.get())
        cfg.cylinder.height = float(self.height_var.get())
        cfg.target.rx = float(self.roi_var.get())
        cfg.target.ry = float(self.roi_var.get())
        cfg.target.rz = float(self.roi_var.get())
        cfg.wire.conductor_width = float(self.cw_var.get())
        cfg.wire.cross_section_a_frac = float(self.a_var.get())
        cfg.wire.cross_section_b_frac = float(self.b_var.get())
        cfg.wire.cross_section_n = int(self.n_var.get())
        # Layer is no longer a GUI control (only relevant for Fusion assets /
        # CLI legacy). Keep the ShellConfig default.
        cfg.control.run_gradient = self.run_gradient_var.get()
        cfg.control.run_leads = self.run_leads_var.get()
        cfg.control.run_shell = self.run_shell_var.get()
        if self.shell_mode_var.get() == 'custom':
            a = self.custom_a_var.get().strip()
            b = self.custom_b_var.get().strip()
            if a and b:
                cfg.shell.use_custom_stl = True
                cfg.shell.custom_stl_a = a
                cfg.shell.custom_stl_b = b
        else:
            # Autogenerated hollow cylinder: editable margin (% of cable height).
            if hasattr(self, 'margin_var'):
                try:
                    cfg.shell.auto_margin_pct = float(self.margin_var.get()) / 100.0
                except ValueError:
                    pass
        # Advanced leads knobs (optional; only override if shown & valid).
        if getattr(self, 'adv_visible', None) and self.adv_visible.get():
            try:
                cfg.leads.wire_tangent_run = float(self.wire_tangent_run_var.get())
            except ValueError:
                pass
            try:
                cfg.leads.cs_blend_rings = int(self.cs_blend_rings_var.get())
            except ValueError:
                pass
            try:
                cfg.leads.junction_rigid_steps = int(self.junction_rigid_steps_var.get())
            except ValueError:
                pass
        return cfg

    def _ask_user(self, question: str) -> bool:
        """Runs on the main thread via root.after; returns user's accept/reject."""
        return messagebox.askyesno("Colision de cables", question)

    def _on_run(self):
        out_dir = self.get_output_dir()
        if not out_dir:
            messagebox.showwarning("Falta directorio",
                                   "Seleccione un directorio de salida primero.")
            return
        try:
            cfg = self._build_cfg()
        except (ValueError, KeyError) as exc:
            messagebox.showerror("Parametros invalidos", str(exc))
            return
        cfg.output_dir = out_dir

        # The overlap check happens inside run_gradient. We hand the runner's
        # ask_user through so a popup appears when collisions are detected.
        def _target(ask_user=None):
            from run_pipeline import run_pipeline as _run
            # run_pipeline doesn't take ask_user; overlap is only reported in
            # the log. The accept/reject is surfaced as a post-run summary.
            return _run(cfg)

        def _on_done(result, err):
            if err is not None:
                messagebox.showerror("Pipeline", f"Fallo: {err}")
            else:
                messagebox.showinfo("Pipeline", f"Listo.\nResultados en:\n{result}")

        self.runner.run(_target, on_done=_on_done, ask_user=self._ask_user)
