"""
Pipeline panel — full gradient + leads + shell run.

Lets the user pick the gradient axis, dimensions, Tikhonov, levels, wire
characteristics, and whether to carve into a custom STL or the autogenerated
cylinder / Fusion shell halves. Runs the three steps in a worker thread and
surfaces the wire-overlap report as an accept/reject popup.
"""

from __future__ import annotations

import os
import tkinter as tk
from tkinter import filedialog, messagebox, ttk
from typing import Optional

from coilgen.config import Config
from .runner import WorkerRunner


class PipelinePanel(ttk.Frame):
    def __init__(self, master, get_output_dir, set_output_dir, root):
        super().__init__(master)
        self.get_output_dir = get_output_dir
        self.set_output_dir = set_output_dir
        self.root = root
        self.runner: Optional[WorkerRunner] = None

        self._build()

    def _build(self):
        body = ttk.Frame(self)
        body.pack(fill='both', expand=True, padx=8, pady=6)
        body.columnconfigure(0, weight=1)
        body.columnconfigure(1, weight=0)
        body.rowconfigure(0, weight=1)

        left_shell = ttk.Frame(body)
        left_shell.grid(row=0, column=0, sticky='nsew')

        left_canvas = tk.Canvas(left_shell, highlightthickness=0)
        left_scroll = ttk.Scrollbar(left_shell, orient='vertical',
                                    command=left_canvas.yview)
        left_canvas.configure(yscrollcommand=left_scroll.set)
        left_canvas.pack(side='left', fill='both', expand=True)
        left_scroll.pack(side='right', fill='y')

        left = ttk.Frame(left_canvas)
        left_window = left_canvas.create_window((0, 0), window=left, anchor='nw')
        left.bind('<Configure>', lambda _e: left_canvas.configure(
            scrollregion=left_canvas.bbox('all')))
        left_canvas.bind('<Configure>', lambda e: left_canvas.itemconfigure(
            left_window, width=e.width))

        form = ttk.LabelFrame(left, text="Pipeline completo", padding=10)
        form.pack(fill='x', pady=(0, 6))
        for col in range(4):
            form.columnconfigure(col, weight=1)

        # Axis
        ttk.Label(form, text="Eje gradiente:").grid(row=0, column=0, sticky='w', padx=4, pady=4)
        self.axis_var = tk.StringVar(value='x')
        ttk.Combobox(form, textvariable=self.axis_var, values=['x', 'y', 'z'],
                     state='readonly', width=6).grid(row=0, column=1, sticky='w')

        # Dimensions
        ttk.Label(form, text="Radio externo cilindro [m]:").grid(row=1, column=0, sticky='w', padx=4, pady=4)
        self.radius_var = tk.StringVar(value='0.039')
        ttk.Entry(form, textvariable=self.radius_var, width=10).grid(row=1, column=1, sticky='w')
        ttk.Label(form, text="Altura cilindro [m]:").grid(row=1, column=2, sticky='w', padx=4)
        self.height_var = tk.StringVar(value='0.430')
        ttk.Entry(form, textvariable=self.height_var, width=10).grid(row=1, column=3, sticky='w')
        ttk.Label(form, text="Radio ROI [m]:").grid(row=2, column=0, sticky='w', padx=4, pady=4)
        self.roi_var = tk.StringVar(value='0.125')
        ttk.Entry(form, textvariable=self.roi_var, width=10).grid(row=2, column=1, sticky='w')

        # Optimization
        ttk.Label(form, text="Tikhonov:").grid(row=3, column=0, sticky='w', padx=4, pady=4)
        self.tikhonov_var = tk.StringVar(value='2500')
        ttk.Entry(form, textvariable=self.tikhonov_var, width=10).grid(row=3, column=1, sticky='w')
        ttk.Label(form, text="Niveles (vueltas):").grid(row=3, column=2, sticky='w', padx=4)
        self.levels_var = tk.StringVar(value='26')
        ttk.Entry(form, textvariable=self.levels_var, width=10).grid(row=3, column=3, sticky='w')

        # Wire characteristics
        ttk.Label(form, text="Diametro conductor [m]:").grid(row=4, column=0, sticky='w', padx=4, pady=4)
        self.cw_var = tk.StringVar(value='0.002')
        ttk.Entry(form, textvariable=self.cw_var, width=10).grid(row=4, column=1, sticky='w')
        ttk.Label(form, text="Seccion A:").grid(row=4, column=2, sticky='w', padx=4)
        self.a_var = tk.StringVar(value='2.0')
        ttk.Entry(form, textvariable=self.a_var, width=8).grid(row=4, column=3, sticky='w')
        ttk.Label(form, text="Seccion B:").grid(row=5, column=0, sticky='w', padx=4, pady=4)
        self.b_var = tk.StringVar(value='1.0')
        ttk.Entry(form, textvariable=self.b_var, width=8).grid(row=5, column=1, sticky='w')
        ttk.Label(form, text="Seccion N:").grid(row=5, column=2, sticky='w', padx=4)
        self.n_var = tk.StringVar(value='16')
        ttk.Entry(form, textvariable=self.n_var, width=8).grid(row=5, column=3, sticky='w')

        # Custom STL vs autogenerated
        self.shell_mode_var = tk.StringVar(value='auto')  # 'auto' or 'custom'
        ttk.Radiobutton(form, text="Cilindro hueco autogenerado (1 pieza)",
                        variable=self.shell_mode_var, value='auto',
                        command=self._toggle_shell).grid(row=7, column=0, columnspan=2, sticky='w', padx=4, pady=4)
        ttk.Radiobutton(form, text="STL custom para impresion (2 mitades)",
                        variable=self.shell_mode_var, value='custom',
                        command=self._toggle_shell).grid(row=7, column=2, columnspan=2, sticky='w')
        self.custom_a_var = tk.StringVar(value='')
        self.custom_b_var = tk.StringVar(value='')
        ttk.Label(form, text="Mitad A:").grid(row=8, column=0, sticky='w', padx=4, pady=2)
        self.custom_a_entry = ttk.Entry(form, textvariable=self.custom_a_var, width=34)
        self.custom_a_entry.grid(row=8, column=1, columnspan=2, sticky='we', padx=4)
        self.custom_a_btn = ttk.Button(form, text="Examinar...",
                                       command=lambda: self._pick_custom('a'))
        self.custom_a_btn.grid(row=8, column=3, padx=4)
        ttk.Label(form, text="Mitad B:").grid(row=9, column=0, sticky='w', padx=4, pady=2)
        self.custom_b_entry = ttk.Entry(form, textvariable=self.custom_b_var, width=34)
        self.custom_b_entry.grid(row=9, column=1, columnspan=2, sticky='we', padx=4)
        self.custom_b_btn = ttk.Button(form, text="Examinar...",
                                       command=lambda: self._pick_custom('b'))
        self.custom_b_btn.grid(row=9, column=3, padx=4)
        # Radial peel removed from each face after boolean (% of cable radial height).
        ttk.Label(form, text="Recorte radial (% alto cable):").grid(
            row=10, column=0, sticky='w', padx=4, pady=2)
        self.margin_var = tk.StringVar(value='50')
        self.margin_entry = ttk.Entry(form, textvariable=self.margin_var, width=6)
        self.margin_entry.grid(row=10, column=1, sticky='w')
        ttk.Label(form, text="Gap entre capas [mm]:").grid(
            row=11, column=0, sticky='w', padx=4, pady=2)
        self.layer_gap_var = tk.StringVar(value='0')
        ttk.Entry(form, textvariable=self.layer_gap_var, width=6).grid(
            row=11, column=1, sticky='w')
        self._toggle_shell()

        # Cross-section previews (reactive to conductor / radius / groove settings).
        preview = ttk.Frame(left)
        preview.pack(fill='x', pady=4)

        xsec = ttk.LabelFrame(preview, text="Seccion transversal", padding=6)
        xsec.pack(side='left', fill='both', expand=True, padx=(0, 4))
        self.xsec_canvas = tk.Canvas(xsec, width=240, height=160,
                                     bg='white', highlightthickness=1,
                                     highlightbackground='#cccccc')
        self.xsec_canvas.pack(side='left', padx=(4, 8))
        info = ttk.Frame(xsec)
        info.pack(side='left', fill='y')
        self.xsec_major_lbl = ttk.Label(info, text="Eje mayor: -")
        self.xsec_major_lbl.pack(anchor='w')
        self.xsec_minor_lbl = ttk.Label(info, text="Eje menor: -")
        self.xsec_minor_lbl.pack(anchor='w')
        self.xsec_n_lbl = ttk.Label(info, text="Vertices: -")
        self.xsec_n_lbl.pack(anchor='w')

        cylsec = ttk.LabelFrame(preview, text="Corte radial cilindro", padding=6)
        cylsec.pack(side='left', fill='both', expand=True, padx=(4, 0))
        self.cyl_canvas = tk.Canvas(cylsec, width=280, height=220,
                                    bg='white', highlightthickness=1,
                                    highlightbackground='#cccccc')
        self.cyl_canvas.pack(side='left', padx=(4, 8), fill='both', expand=True)
        cyl_info = ttk.Frame(cylsec)
        cyl_info.pack(side='left', fill='y')
        self.cyl_outer_lbl = ttk.Label(cyl_info, text="R externo final: -")
        self.cyl_outer_lbl.pack(anchor='w')
        self.cyl_design_lbl = ttk.Label(cyl_info, text="R interno estimado: -")
        self.cyl_design_lbl.pack(anchor='w')
        self.cyl_wire_lbl = ttk.Label(cyl_info, text="Espesor shell: -")
        self.cyl_wire_lbl.pack(anchor='w')
        self.cyl_shell_lbl = ttk.Label(cyl_info, text="Alto cable: -")
        self.cyl_shell_lbl.pack(anchor='w')
        self.cyl_status_lbl = ttk.Label(cyl_info, text="")
        self.cyl_status_lbl.pack(anchor='w')

        for var in (self.radius_var, self.cw_var, self.a_var, self.b_var,
                    self.n_var, self.margin_var, self.layer_gap_var):
            var.trace_add('write', lambda *_: self._redraw_previews())
        self.xsec_canvas.bind('<Configure>', lambda _e: self._redraw_xsec_preview())
        self.cyl_canvas.bind('<Configure>', lambda _e: self._redraw_cylinder_preview())
        self._redraw_previews()

        # Steps toggles
        steps = ttk.LabelFrame(left, text="Pasos", padding=6)
        steps.pack(fill='x', pady=4)
        self.run_gradient_var = tk.BooleanVar(value=True)
        self.run_leads_var = tk.BooleanVar(value=True)
        self.run_shell_var = tk.BooleanVar(value=True)
        self.overlap_var = tk.BooleanVar(value=True)
        ttk.Checkbutton(steps, text="Gradiente (pyCoilGen)", variable=self.run_gradient_var).pack(side='left', padx=6)
        ttk.Checkbutton(steps, text="Leads", variable=self.run_leads_var).pack(side='left', padx=6)
        ttk.Checkbutton(steps, text="Shell", variable=self.run_shell_var).pack(side='left', padx=6)
        ttk.Checkbutton(steps, text="Alertar colisiones", variable=self.overlap_var).pack(side='left', padx=6)

        # Advanced leads (collapsible)
        self.adv_frame = ttk.LabelFrame(left, text="Leads avanzado", padding=6)
        self.adv_frame.pack(fill='x', pady=4)
        self.adv_visible = tk.BooleanVar(value=False)
        self.adv_toggle = ttk.Checkbutton(
            self.adv_frame, text="Mostrar parametros avanzados de leads",
            variable=self.adv_visible, command=self._toggle_advanced)
        self.adv_toggle.pack(anchor='w')
        self.adv_body = ttk.Frame(self.adv_frame)
        # lead_blend [m] (cubic Bezier handle floor for the smooth lead curve)
        ttk.Label(self.adv_body, text="lead_blend [m]:").grid(
            row=0, column=0, sticky='w', padx=4, pady=2)
        self.lead_blend_var = tk.StringVar(value='0.015')
        ttk.Entry(self.adv_body, textvariable=self.lead_blend_var,
                  width=10).grid(row=0, column=1, sticky='w')
        # cs_blend_rings
        ttk.Label(self.adv_body, text="cs_blend_rings:").grid(
            row=0, column=2, sticky='w', padx=8, pady=2)
        self.cs_blend_rings_var = tk.StringVar(value='20')
        ttk.Entry(self.adv_body, textvariable=self.cs_blend_rings_var,
                  width=6).grid(row=0, column=3, sticky='w')
        # junction_rigid_steps
        ttk.Label(self.adv_body, text="junction_rigid_steps:").grid(
            row=0, column=4, sticky='w', padx=8, pady=2)
        self.junction_rigid_steps_var = tk.StringVar(value='4')
        ttk.Entry(self.adv_body, textvariable=self.junction_rigid_steps_var,
                  width=6).grid(row=0, column=5, sticky='w')
        self._toggle_advanced()

        # Run button
        bar = ttk.Frame(left)
        bar.pack(fill='x', pady=4)
        self.run_btn = ttk.Button(bar, text="Correr pipeline", command=self._on_run)
        self.run_btn.pack(side='left')
        self.stop_btn = ttk.Button(bar, text="Detener", command=self._on_stop)
        self.progress = ttk.Progressbar(bar, mode='determinate', maximum=100, length=260)
        self.progress.pack(side='left', padx=10, fill='x', expand=True)

        # Log (right column -- fixed beside the scrollable controls/previews)
        log_frame = ttk.LabelFrame(body, text="Log", padding=4)
        log_frame.grid(row=0, column=1, sticky='ns', padx=(8, 0))
        self.log_text = tk.Text(log_frame, width=42, wrap='word')
        self.log_text.pack(side='left', fill='both', expand=True)
        sb = ttk.Scrollbar(log_frame, command=self.log_text.yview)
        sb.pack(side='right', fill='y')
        self.log_text.configure(yscrollcommand=sb.set)

        self.runner = WorkerRunner(self.log_text, self.progress, self.root)

    def _toggle_advanced(self):
        if self.adv_visible.get():
            self.adv_body.pack(fill='x', padx=4, pady=4)
        else:
            self.adv_body.pack_forget()

    def _toggle_shell(self):
        custom = self.shell_mode_var.get() == 'custom'
        state = 'normal' if custom else 'disabled'
        self.custom_a_entry.configure(state=state)
        self.custom_a_btn.configure(state=state)
        self.custom_b_entry.configure(state=state)
        self.custom_b_btn.configure(state=state)
        # Margin field (added with the auto hollow-cylinder) is enabled only
        # in autogenerated mode.
        margin_state = 'normal' if not custom else 'disabled'
        if hasattr(self, 'margin_entry'):
            self.margin_entry.configure(state=margin_state)

    def _pick_custom(self, half: str):
        path = filedialog.askopenfilename(
            title=f"Seleccionar STL mitad {half.upper()} de shell",
            filetypes=[("STL", "*.stl"), ("All", "*.*")],
        )
        if path:
            if half == 'a':
                self.custom_a_var.set(path)
            else:
                self.custom_b_var.set(path)

    def _preview_cfg(self) -> Config:
        cfg = Config(gradient_axis=self.axis_var.get(), show_plots=False)
        cfg.cylinder.radius = float(self.radius_var.get())
        cfg.wire.conductor_width = float(self.cw_var.get())
        cfg.wire.cross_section_a_frac = float(self.a_var.get())
        cfg.wire.cross_section_b_frac = float(self.b_var.get())
        cfg.wire.cross_section_n = int(self.n_var.get())
        cfg.shell.auto_margin_pct = float(self.margin_var.get()) / 100.0
        cfg.winding.layer_gap_mm = float(self.layer_gap_var.get()) / 1000.0
        cfg.winding.normal_shift = None
        return cfg

    def _redraw_previews(self):
        self._redraw_xsec_preview()
        self._redraw_cylinder_preview()

    def _redraw_xsec_preview(self):
        """Draw the conductor's elliptical cross-section on the preview canvas.

        Parametric profile: x = (A*cw/2)*sin(theta), y = (B*cw/2)*cos(theta).
        Rotated 90° for display so the major axis (A) is vertical, matching
        the STL. With A=B=1, cw is the displayed conductor diameter.
        """
        c = self.xsec_canvas
        try:
            cfg = self._preview_cfg()
        except ValueError:
            c.delete('all')
            c.create_text(c.winfo_width() // 2 or 120, 80,
                          text="Entradas invalidas", fill='#aa0000')
            return
        c.delete('all')
        w = max(c.winfo_width(), 60)
        h = max(c.winfo_height(), 60)
        semi_major = cfg.conductor_semi_a   # A — tall axis in the coil frame
        semi_minor = cfg.conductor_semi_b   # B — wide axis in the coil frame
        major = 2 * semi_major
        minor = 2 * semi_minor
        self.xsec_major_lbl.config(text=f"Alto radial (A): {major*1000:.3f} mm")
        self.xsec_minor_lbl.config(text=f"Ancho axial (B): {minor*1000:.3f} mm")
        self.xsec_n_lbl.config(
            text=(f"Vertices: {cfg.wire.cross_section_n}  |  "
                  f"D nominal: {cfg.wire.conductor_width*1000:.3f} mm"))
        if semi_major <= 0 or semi_minor <= 0:
            return
        margin = 22
        avail_w = w - 2 * margin
        avail_h = h - 2 * margin
        # 90° rotation: major vertical, minor horizontal.
        scale = min(avail_w / minor, avail_h / major) if major > 0 and minor > 0 else 0
        if scale <= 0:
            return
        cx, cy = w / 2, h / 2
        rx = semi_minor * scale   # horizontal on canvas
        ry = semi_major * scale   # vertical on canvas
        # Axes
        c.create_line(margin, cy, w - margin, cy, fill='#bbbbbb', dash=(3, 3))
        c.create_line(cx, margin, cx, h - margin, fill='#bbbbbb', dash=(3, 3))
        # Ellipse: swap sin/cos mapping so A aligns with canvas Y.
        import math
        pts = []
        for i in range(cfg.wire.cross_section_n):
            th = 2 * math.pi * i / cfg.wire.cross_section_n
            pts.append(cx + rx * math.cos(th))
            pts.append(cy - ry * math.sin(th))
        if len(pts) >= 6:
            c.create_polygon(*pts, outline='#0066cc', fill='#cfe8ff', width=1.5)
        # Dimension annotations (major vertical, minor horizontal)
        c.create_text(12, cy, angle=90, text=f"{major*1000:.3f} mm", fill='#333333')
        c.create_text(cx, 12, text=f"{minor*1000:.3f} mm", fill='#333333')

    def _redraw_cylinder_preview(self):
        """Draw shell annulus and schematic grooves (single-radius model)."""
        c = self.cyl_canvas
        try:
            cfg = self._preview_cfg()
        except ValueError:
            c.delete('all')
            c.create_text(c.winfo_width() // 2 or 140, 80,
                          text="Entradas invalidas", fill='#aa0000')
            return

        c.delete('all')
        w = max(c.winfo_width(), 80)
        h = max(c.winfo_height(), 80)
        r_outer = cfg.shell_outer_radius
        r_inner = cfg.shell_inner_radius
        design_r = cfg.cylinder_design_radius
        peel = cfg.radial_peel
        shift = cfg.normal_shift_length
        inner_layer_r = design_r + shift
        wall_thickness = cfg.shell_wall_thickness
        gap_mm = cfg.layer_crossing_gap * 1000.0
        wire_outer = cfg.estimated_wire_outer_radius
        wire_inner = cfg.estimated_wire_inner_radius
        groove_floor = wire_inner

        self.cyl_outer_lbl.config(
            text=f"R externo: {r_outer*1000:.1f} mm")
        self.cyl_design_lbl.config(
            text=f"R interno: {r_inner*1000:.1f} mm")
        self.cyl_wire_lbl.config(
            text=f"Grosor: {wall_thickness*1000:.2f} mm  "
                 f"(2h+gap-2x{peel*1000:.1f})")
        self.cyl_shell_lbl.config(
            text=(f"Alto radial: {cfg.cable_height*1000:.2f} mm  |  "
                  f"Gap capas: {gap_mm:.2f} mm"))

        degenerate = (r_outer <= 0 or r_inner <= 0 or design_r <= 0
                      or wall_thickness <= 0 or r_inner >= r_outer)
        if degenerate:
            self.cyl_status_lbl.config(text="Geometria invalida", foreground='#aa0000')
        else:
            self.cyl_status_lbl.config(
                text=(f"centro cable/shell: {cfg.estimated_wire_radial_center*1000:.2f} mm  |  "
                      f"cable {wire_inner*1000:.1f}-{wire_outer*1000:.1f} mm"),
                foreground='#333333')
        if degenerate:
            return

        import math
        pad = 16
        cx, cy = w / 2, h / 2
        scale = min((w - 2 * pad) / (2 * r_outer),
                    (h - 2 * pad) / (2 * r_outer))

        def bbox(radius_m):
            rpx = radius_m * scale
            return (cx - rpx, cy - rpx, cx + rpx, cy + rpx)

        # Shell annulus.
        c.create_oval(*bbox(r_outer), fill='#e8f2ff', outline='#111111', width=2)
        c.create_oval(*bbox(r_inner), fill='white', outline='#111111', width=2)

        # Schematic grooves at pyCoilGen layer centers.
        groove_radial = cfg.cable_height
        groove_tangent = 2.0 * cfg.conductor_semi_b
        gr_px = max(groove_radial * scale, 6.0)
        gt_px = max(groove_tangent * scale, 6.0)
        groove_specs = (
            ("capa ext.", design_r, 42),
            ("capa int.", inner_layer_r, 62),
        )

        def radial_ellipse_points(center_radius, theta, radial_px, tangent_px, n=28):
            gx = cx + center_radius * scale * math.cos(theta)
            gy = cy - center_radius * scale * math.sin(theta)
            rux, ruy = math.cos(theta), -math.sin(theta)
            tux, tuy = -math.sin(theta), -math.cos(theta)
            pts = []
            for i in range(n):
                a = 2.0 * math.pi * i / n
                px = (gx + 0.5 * radial_px * math.cos(a) * rux
                      + 0.5 * tangent_px * math.sin(a) * tux)
                py = (gy + 0.5 * radial_px * math.cos(a) * ruy
                      + 0.5 * tangent_px * math.sin(a) * tuy)
                pts.extend([px, py])
            return pts, gx, gy

        for label, center_radius, deg in groove_specs:
            th = math.radians(deg)
            pts, gx, gy = radial_ellipse_points(center_radius, th, gr_px, gt_px)
            c.create_polygon(*pts, fill='#f5fbff', outline='#8a5a00', width=1.5)
            c.create_text(gx + 4, gy - 10, anchor='w', text=label,
                          fill='#8a5a00', font=('', 8))

        # Groove floor (innermost wire face) when margin reduces wall below full 2h+gap.
        if peel > 0 and groove_floor < r_inner:
            c.create_oval(*bbox(groove_floor), outline='#8a5a00', width=1, dash=(4, 3))

        r_outer_px = r_outer * scale
        r_inner_px = r_inner * scale
        c.create_text(cx - r_outer_px * 0.42, cy + r_outer_px * 0.16,
                      text=f"R ext\n{r_outer*1000:.1f} mm",
                      fill='#111111', justify='center', font=('', 8))
        c.create_text(cx + r_inner_px * 0.34, cy - r_inner_px * 0.34,
                      text=f"R int\n{r_inner*1000:.1f} mm",
                      fill='#111111', justify='center', font=('', 8))

    def _build_cfg(self) -> Config:
        cfg = Config(
            gradient_axis=self.axis_var.get(),
            tikhonov_factor=float(self.tikhonov_var.get()),
            num_levels=int(self.levels_var.get()),
            show_plots=False,
            overlap_warn=self.overlap_var.get(),
        )
        cfg.cylinder.radius = float(self.radius_var.get())
        cfg.cylinder.height = float(self.height_var.get())
        cfg.target.rx = float(self.roi_var.get())
        cfg.target.ry = float(self.roi_var.get())
        cfg.target.rz = float(self.roi_var.get())
        cfg.wire.conductor_width = float(self.cw_var.get())
        cfg.wire.cross_section_a_frac = float(self.a_var.get())
        cfg.wire.cross_section_b_frac = float(self.b_var.get())
        cfg.wire.cross_section_n = int(self.n_var.get())
        cfg.shell.shell_outer_pad = max(0.0005, 0.65 * cfg.conductor_semi_a)
        try:
            cfg.winding.layer_gap_mm = float(self.layer_gap_var.get()) / 1000.0
            cfg.winding.normal_shift = None
        except ValueError:
            pass
        # Layer is no longer a GUI control (only relevant for Fusion assets /
        # CLI legacy). Keep the ShellConfig default.
        cfg.control.run_gradient = self.run_gradient_var.get()
        cfg.control.run_leads = self.run_leads_var.get()
        cfg.control.run_shell = self.run_shell_var.get()
        if self.shell_mode_var.get() == 'custom':
            a = self.custom_a_var.get().strip()
            b = self.custom_b_var.get().strip()
            if a and b:
                cfg.shell.use_custom_stl = True
                cfg.shell.custom_stl_a = a
                cfg.shell.custom_stl_b = b
        else:
            # Autogenerated hollow cylinder: editable margin (% of cable height).
            if hasattr(self, 'margin_var'):
                try:
                    cfg.shell.auto_margin_pct = float(self.margin_var.get()) / 100.0
                except ValueError:
                    pass
        if cfg.cylinder.radius <= 0 or cfg.cylinder_design_radius <= 0:
            raise ValueError(
                "El radio externo del cilindro debe ser mayor que el semi-eje A del cable.")
        if (not cfg.shell.use_custom_stl
                and cfg.estimated_shell_thickness <= 0):
            raise ValueError(
                "La combinacion de radio, alto de cable y separacion de capas "
                "deja el cilindro autogenerado sin espesor radial util.")
        # Advanced leads knobs (optional; only override if shown & valid).
        if getattr(self, 'adv_visible', None) and self.adv_visible.get():
            try:
                cfg.leads.lead_blend = float(self.lead_blend_var.get())
            except ValueError:
                pass
            try:
                cfg.leads.cs_blend_rings = int(self.cs_blend_rings_var.get())
            except ValueError:
                pass
            try:
                cfg.leads.junction_rigid_steps = int(self.junction_rigid_steps_var.get())
            except ValueError:
                pass
        return cfg

    def _ask_user(self, question: str) -> bool:
        """Runs on the main thread via root.after; returns user's accept/reject."""
        return messagebox.askyesno("Colision de cables", question)

    def _set_running(self, running: bool):
        self.run_btn.configure(state='disabled' if running else 'normal')
        if running:
            self.stop_btn.configure(state='normal', text="Detener")
            if not self.stop_btn.winfo_ismapped():
                self.stop_btn.pack(side='left', padx=(6, 0), before=self.progress)
        else:
            if self.stop_btn.winfo_ismapped():
                self.stop_btn.pack_forget()

    def _on_stop(self):
        if self.runner is not None:
            self.runner.request_stop()
        self.stop_btn.configure(state='disabled', text="Deteniendo...")

    def _on_run(self):
        out_dir = self.get_output_dir()
        if not out_dir:
            messagebox.showwarning("Falta directorio",
                                   "Seleccione un directorio de salida primero.")
            return
        try:
            cfg = self._build_cfg()
        except (ValueError, KeyError) as exc:
            messagebox.showerror("Parametros invalidos", str(exc))
            return
        cfg.output_dir = out_dir
        self._set_running(True)

        # The overlap check happens inside run_gradient. We hand the runner's
        # ask_user through so a popup appears when collisions are detected.
        def _target(ask_user=None):
            from run_pipeline import run_pipeline as _run
            return _run(cfg, should_stop=self.runner.should_stop)

        def _on_done(result, err):
            self._set_running(False)
            if err is not None:
                messagebox.showerror("Pipeline", f"Fallo: {err}")
            else:
                messagebox.showinfo("Pipeline", f"Listo.\nResultados en:\n{result}")

        self.runner.run(_target, on_done=_on_done, ask_user=self._ask_user)
